### ISSUE TITLE
Enhance KEM skeleton to support Hybrid KEM operations

### ISSUE THREAD

**Issue by nhorman** [openssl/project#1011]
Enhance ML-KEM skeleton to support hybrid KEM operations.  Hybrid key should be an EVP object that holds two generic EVP_PKEY objects, must support X25519-MLKEM768 and P256-MLKEM768

This Issues covers the KEM aspect of the implementation - i.e. this is the KEM interface in the providers

completion of this work is predicated on https://github.com/openssl/project/issues/1021 and also needs completion of openssl/project#1012.

"Design": 

- Extending the code in https://github.com/openssl/openssl/pull/25640 KEM logic shall be developed that
  - uses two generic EVP_PKEY structures as per openssl/project#1012, incl. public and private key material, e.g., generating two keys instead of one when requested, responding to all key management operations triggering corresponding actions on both objects; the reported security strength should be the minimum of the two constituent security strengths; the returned encoded public key shall be the concatenation of the constituent encoded public keys
  - operate these two EVP_PKEYs as a single KEM in the following way: Do two KEM encap/decap operations instead of one, encapsulating/decapsulating the concatenation of the two shared secrets as per https://www.ietf.org/archive/id/draft-kwiatkowski-tls-ecdhe-mlkem-02.html#name-x25519mlkem768

If there are not sufficient generic EVP API calls available to do this in a truly generic way, focus on algorithms requiring no parameters for management and operation (x25519, x448, PQ KEMs) as well as EC-P algorithms. Ultimate goal is the instantiation of X25519MLKEM768 and P256MLKEM768 hybrids, but for test purposes, instantiation of an artificial X25519X448 hybrid KEM may also be possible/used for test purposes.

Note: This is a compile time concept, not run time selectable

**Comment by t8m** [comment]
> Enhance ML-KEM shell to support hybrid operations. Hybrid key should be an EVP object that holds two generic EVP_PKEY objects, must support X25519-MLKEM768 and P256-MLKEM768

IMO this is wrong. It should not be implemented on the libcrypto side. As far as what I understand what we were talking about on Tuesday was that there would be a generic hybrid KEM provider implementation that would use EVP calls to fetch the two underlying KEM implementations and just concatenate the the calls and the data (be it a key data or the encapsulated/decapsulated data).

**Comment by baentsch** [comment]
> > Enhance ML-KEM shell to support hybrid operations. Hybrid key should be an EVP object that holds two generic EVP_PKEY objects, must support X25519-MLKEM768 and P256-MLKEM768
> 
> IMO this is wrong. It should not be implemented on the libcrypto side. As far as what I understand what we were talking about on Tuesday was that there would be a generic hybrid KEM provider implementation that would use EVP calls to fetch the two underlying KEM implementations and just concatenate the the calls and the data (be it a key data or the encapsulated/decapsulated data).

The proposal on Tue was to create a generic hybrid key manager and KEM operator, independent from and external to ML-KEM logic, ideally only using EVP API calls. Nevertheless this was meant to become part of default provider: As such I'd consider it part of libcrypto: If this understanding is wrong (that default provider is part of libcrypto) then your statement is completely right, @t8m.

**Comment by t8m** [comment]
The default provider is of course effectively part of libcrypto and what you wrote above does not conflict with what I am saying.

What does not make sense to me is this sentence: *Hybrid key should be an EVP object that holds two generic EVP_PKEY objects, must support X25519-MLKEM768 and P256-MLKEM768.* From the point of view of libcrypto EVP API implementation this should be completely transparent so a hybrid key is just an EVP_PKEY as any other provider based EVP_PKEY. The EVP layer in libcrypto should NOT be aware of the internals. This sentence, at least in some possible interpretations, sounds like this would be implemented at the EVP layer in libcrypto, which would be wrong.

**Comment by t8m** [comment]
Also I am not sure how this is predicated on openssl/project#1021 - this should be IMO a separate implementation from the ML-KEM shell.

**Comment by nhorman** [comment]
My understanding matched @t8m .  I was under the impression that the shell (to use the above term) would be an implementation of the provider api, for which the EVP api would be able to manipulate the implemented objects.

@t8m to your question above it was my assumption that the implementation of the shell was a predicate to doing hybrid KEM operations as the hybrid work would rely on the existance of the ML-KEM ops.

**Comment by t8m** [comment]
You could even test it by combining two non-pqc algorithms so there is no requirement to have any PQC KEM implemented.

**Comment by baentsch** [comment]
> this should be IMO a separate implementation from the ML-KEM shell.

completely agree. My initially suggested work item was a generic KEM shell (with generic tracing capabilities) for _any_ KEM implementor to build on, not just an MLKEM one. And us(ed) to build MLKEM and Hybrid (separately) on.

**Comment by nhorman** [comment]
ok, so is my (new) understanding that the "shell" is really just an API capable of implementing generic KEM operations, and exists independently of any provider infrastructure?  i.e. creating the provider logic to marry the EVP apis to the ML-KEM shell is a separate task?

**Comment by baentsch** [comment]
Yes; like this:

```
|--------------------------------------------|
|   X25519MLKEM768  | P256MLKEM768 |  .....  |
|--------------------------------------------|
| MLKEM KEM+KM | Hybrid KEM+KM | EC/X KEM+KM |
|--------------------------------------------|
|         generic KEM+KM with tracing        |
|--------------------------------------------|
```

> exists independently of any provider infrastructure

Not exactly: It implements [KM](https://docs.openssl.org/master/man7/provider-keymgmt/) and [KEM](https://docs.openssl.org/master/man7/provider-kem/) provider capabilities and as such can be(come) part of any provider (incl. default and fips).

**Comment by baentsch** [comment]
As discussed in Monday's standup, WIP implementation now accessible in https://github.openssl.org/mbaentsch/openssl/tree/mb-hybrid-km-kem. Will keep adding code as time permits. Other eyes & contributions _very_ welcome.

**Comment by baentsch** [comment]
Issue would be superseded/resolved by https://github.com/openssl/openssl/issues/25884 if done there.

**Comment by vavroch2010** [comment]
Duplicate https://github.com/openssl/openssl/issues/25884
