### ISSUE TITLE
Enhance key management skeleton to support use of hybrid keys

### ISSUE THREAD

**Issue by nhorman** [openssl/project#1012]
Based on openssl/project#1021 implement key management functionality for generic hybrid EVP_PKEY operation, supporting at the least EC P256, P384, and X25519. Shall also work with any other parameter-less algorithms, incl. MLKEM.

"Design":

- Extending the code in https://github.com/openssl/openssl/pull/25640 a key manager shall be developed that
  - can maintain two generic EVP_PKEY structures, incl. public and private key material, e.g., generating two keys instead of one when requested, responding to all key management operations triggering corresponding actions on both objects; the reported security strength should be the minimum of the two constituent security strengths; the returned encoded public key shall be the concatenation of the constituent encoded public keys
  - enable operation of these two EVP_PKEYs as a single KEM in the following way: Do two KEM encap/decap operations instead of one, encapsulating/decapsulating the concatenation of the two shared secrets as per https://www.ietf.org/archive/id/draft-kwiatkowski-tls-ecdhe-mlkem-02.html#name-x25519mlkem768

If there are not sufficient generic EVP API calls available to do this in a truly generic way, focus on algorithms requiring no parameters for management and operation (x25519, x448, PQ KEMs) as well as EC-P algorithms. Ultimate goal is the instantiation of X25519MLKEM768 and P256MLKEM768 hybrids, but for test purposes, instantiation of an artificial X25519X448 hybrid KEM may also be possible/used for test purposes.

Note: This is a compile time concept, not run time selectable

**Comment by baentsch** [comment]
Issue would be superseded/resolved by https://github.com/openssl/openssl/issues/25884 if done there.
