### ISSUE TITLE
extend evp tests for ML-KEM768

### ISSUE THREAD

**Issue by nhorman** [openssl/project#1013]
Add any known answer tests into the evp_test harness in our test environment

@baentsch please add reference to the spec containing known answers here. Done below.

Note: This is non-hybrid kem tests only

The work effort for this can be split by first doing openssl/project#1015 and depends on the completion of openssl/project#1014.

**Comment by baentsch** [comment]
https://pages.nist.gov/ACVP/draft-celi-acvp-ml-kem.html (ACVP) and https://csrc.nist.gov/Projects/Post-Quantum-Cryptography/Post-Quantum-Cryptography-Standardization/Example-Files (KATs).

fwiw, OQS only stores (and compares) hashes to be efficient in terms of data size stored in GH, see https://github.com/open-quantum-safe/liboqs/blob/main/tests/KATs/kem/kats.json. Interop against this would be sufficient for starters, I'd gather (before integrating the full ACVP test set). Sample code in https://github.com/open-quantum-safe/liboqs/blob/main/tests/kat_kem.c and https://github.com/open-quantum-safe/liboqs/blob/main/tests/test_kat.py

**Comment by baentsch** [comment]
Replaced by openssl/project#1045
