### ISSUE TITLE
Implement MLKEM (first, -768) KAT tests against MLKEM crypto API

### ISSUE THREAD

**Issue by baentsch** [openssl/project#1015]
Making the work in openssl/project#1013 more manageable this is to propose doing KAT tests against the low-level crypto API for MLKEM separately. All work obtaining test vectors, running tests and confirming correctness, e.g., JSON parsing etc. could be done as part of resolving this task and then be re-used in openssl/project#1013 when testing against the EVP API, thus validating the whole integration.

This is a reversal of my previous position (to do KAT testing only at the EVP level to be efficient) in recognition of the need to split work onto more shoulders.

**Comment by baentsch** [comment]
@andrewkdinh Do you feel you could work on this? If not, I'll take a stab at this next to gain a little bit of confidence in the correctness of openssl/project#1020

**Comment by andrewkdinh** [comment]
@baentsch Looks like a task I can do. I'll add tests for our current ML-KEM implementation from openssl/project#1020 against the [KAT sample files from NIST](https://csrc.nist.gov/Projects/Post-Quantum-Cryptography/Post-Quantum-Cryptography-Standardization/Example-Files)

**Comment by andrewkdinh** [comment]
PR open here: https://github.openssl.org/mbaentsch/openssl/pull/5

**Comment by andrewkdinh** [comment]
The KAT sample files from NIST are not adequate for testing our ML-KEM 768 API's, so I will instead match the KAT tests BoringSSL has for ML-KEM 768: https://boringssl.googlesource.com/boringssl/+/refs/heads/master/crypto/mlkem
