### ISSUE TITLE
Implement KEM & key management skeleton

### ISSUE THREAD

**Issue by nhorman** [openssl/project#1021]
Make a MLKEM shell capable of instantiating an instance of the ML-KEM768 algorithm.  Follow pattern from @mattcaswell as provided in https://github.com/openssl/openssl/pull/25403#issuecomment-2336397921

Note, this task does not require a full implementation of  ML-KEM.  Rather the implementations can be left empty.  This is meant only to create a skeleton to fill out later with implementation details, as tracked by https://github.com/openssl/project/issues/1020

**Comment by baentsch** [comment]
None of these PQ-related items list the equivalently required [key management shells](https://docs.openssl.org/master/man7/provider-keymgmt/): Why? Is your assumption that the "KEM skeleton" also comprises the required key management parts, @nhorman ?

**Comment by baentsch** [comment]
If you'd like us to use the code in https://github.com/openssl/openssl/pull/25403#issuecomment-2336397921, fine we can also do that. I already enhanced it (adding support for import/export) in https://github.com/baentsch/openssl/tree/mb-mlkem768. Question: How/where to land the "skeleton" code? For now I'll keep it in a new branch in my GH account. Eventually it should land somewhere where other provider users may make use of it. Suggestions for a location welcome, @levitte . Until https://github.com/openssl/openssl/issues/25439 is done, I'll also add (my way :) to trace into the skeleton.

**Comment by nhorman** [comment]
yes, its had been my assumption that it would.  If that was not your understanding, I'm happy to augment the comment to that effect.

In answer to your question, thank you for reminding me, I need to add a task to request a PQ feature branch!

**Comment by baentsch** [comment]
First cut implementing this in https://github.com/openssl/openssl/pull/25640.

As I had originally intended this to be the "blueprint" code for implementing https://github.com/openssl/project/issues/1011 in consequence it has dependencies on (libcrypto) common provider code -- but for people looking for (external) sample provider code this is not sensible. Advice sought as to how to move this forward: Maybe introduce an #ifdef for utilizing (or not) common code? What'd you think @levitte ?
