### ISSUE TITLE
Automatic release staging - Make buildbot behave

### ISSUE THREAD

**Issue by levitte** [openssl/project#12]
Code was added to our buildbots (ci.buildbot.openssl.org) to deploy release staging.  Unfortunately, buildbot is unhappy or has surprising behaviors.  This needs some extended experimentation and fixing.

Currently observed oddities:

* The scheduler for release staging specifies codebases that should work, among others staging-tool for the staging tool repo, which should become part of the source stamps to the builds.  Alas, it's still absent.

* The buildbot source step is...  somewhat lacking.  You're allowed to specify an "origin", thereby specifying a symbolic remote.  However, subsequent fetches of the same source is done by URL, thereby bypassing the symbolic remote entirely.Our code to check if the source in one repository is the ancestor of the same source from another repository cannot work under these conditions, and needs to be refactored to work differently.

**Comment by quarckster** [comment]
This ticket must be closed as non-actual. ci.buildbot.openssl.org is replaced with GitHub Actions and self-hosted runners. Automation buildbot instance (automation.openssl.org) will be replaced with Ansible and Semaphore.

References:

- #378 
- https://github.com/openssl/private/issues/91
