### ISSUE TITLE
Issue Final Release

### ISSUE THREAD

**Issue by arapov** [openssl/project#128]
Release Master: @levitte 
Review: @hlandau 

Release checklist:

- [x] All issues [triaged] as regressions on the development branch from which the
  release is to be done must have a milestone assigned.
  _Regressions are considered from the previous stable release series._
- [x] All issues or pull requests with the milestone for the release are closed.
- [x] There are no outstanding untriaged Coverity issues.
- [x] Coveralls coverage has not decreased overall from the previous release from
  the particular development branch.
- [ ] The CI must pass on the tip of the development branch before the release
  commits are added to the tree, including the daily CI builds.
- [x] The tree must be frozen for at least 7 days. No changes apart from regression
  or security fixes should be merged during the freeze.
- [ ] For 2 days before the release there should be no changes to ensure the daily
  CI builds run on the development tree tip.
- [x] The OTC should explicitly approve that the source is ready for a release with
  a vote.

**Comment by t8m** [comment]
Coverity was waived by OTC vote.

**Comment by levitte** [comment]
Release done
