### ISSUE TITLE
Proprosal for a new performance testing infrastructure

### ISSUE THREAD

**Issue by arapov** [openssl/project#137]
From WG Meeting on 2023-07-23:
```
Hardware for Performance Testing
    - We need a rough (not exact) price quote for an appropriate server
      and a rough (not exact) price quote for more space/power at spacenet
    - AVX512IFMA essential

AI: Anton to create ticket for Alesh to come up with a proprosal for a new
    performance testing infrastructure to be ordered and racked at Spacenet
```

**Comment by hlandau** [comment]
Referencing this from https://github.com/openssl/project/issues/353

While we're planning on buying physical servers dedicated tenancy cloud machines still might be an option, especially if we're only running these once a day or something

**Comment by quarckster** [comment]
We have bought and configured two Supermicro servers. I believe this issue can be closed.
