### ISSUE TITLE
Stricter enforcement of DER encoding

### ISSUE THREAD

**Issue by paulidale** [openssl/project#143]
Refer public issue: openssl/openssl#21620
Refer original security report: [otc/security＃112](https://github.openssl.org/otc/security/issues/112)

**Comment by nhorman** [comment]
@paulidale could you please add a  few sentences here as to what success looks like on this issue?  i.e. outline what additional constraints you would like to see on DER encoding.  That would help me triage and prioritize this issue.  Thanks!

**Comment by nhorman** [comment]
Closing as duplicate of public issue
