### ISSUE TITLE
QUIC: tests for stateless reset handling on receiving side

### ISSUE THREAD

**Issue by t8m** [openssl/project#160]
The connection should be established between the client and the test server, then a correct stateless reset packet should be created and injected into the connection on the server side to be received by the client. The client must then immediately close the connection.

**Comment by nhorman** [comment]
Currently our quic implementation is capable of exchanging stateless reset tokens, but never actually sends them.  As such a test for sending this packet type isn't currently feasible

**Comment by arapov** [comment]
> Currently our quic implementation is capable of exchanging stateless reset tokens, but never actually sends them. As such a test for sending this packet type isn't currently feasible

This issue should be back in backlog then... Can this issue be linked with other work, which is a prerequisite?

**Comment by t8m** [comment]
This is not a request for testing _sending_ the stateless reset tokens but receiving and properly handling them.

The connection should be established between the client and the test server, then a correct stateless reset packet should be created and injected into the connection on the server side to be received by the client. The client must then immediately close the connection.

**Comment by hlandau** [comment]
Looking at the codebase, the situation is as follows:

- We have functionality to detect stateless resets sent by a server. We never generate them.
- We do not have any tests for this. It looks like this may have fallen through the cracks for 3.2. We should fix this.
