### ISSUE TITLE
Craft the ICMC23 presentation before 8/30.

### ISSUE THREAD

**Issue by arapov** [openssl/project#170]
ssia. must be shared with program committee before then.

[Presentation](https://docs.google.com/presentation/d/1Lgm9waAN_hnZeYXhsZRBkjzEeKIHMlhwysT_6yh2M_o/edit)

**Comment by arapov** [comment]
@tomas: (this is the issue, I mentioned)

![Image](https://github.com/openssl/project/assets/1823164/9edbacab-dc9f-46c2-8204-654c21cb9309)

**Comment by tomas** [comment]
@arapov You're talking to the wrong guy. Please don't mention me in this repo again, thanks

**Comment by arapov** [comment]
@tomas, hehe, right! @t8m!

**Comment by t8m** [comment]
This should be fixed already
