### ISSUE TITLE
Enhance network emulation BIO

### ISSUE THREAD

**Issue by hlandau** [openssl/project#179]
<s>Create a BIO_dgram_pair-like BIO, the "netmatic" BIO, which can

- reorder datagrams
- drop datagrams randomly or particular datagrams on command
- impose simulated bandwidth and latency limits
- randomly corrupt datagrams

This will be very useful for testing, and we can replace our use of real BIO_dgrams in our multistream test with this. This will make our tests more reliable and also allow us to test edge cases around retransmission better.</s>

- add support for imposing simulated bandwidth and latency limits
- ~~randomly corrupt datagrams~~
- make multistream test use it, at least under some build configurations

**Comment by t8m** [comment]
Corruption of datagrams especially in the headers area is already present.
