### ISSUE TITLE
FIPS 140-3 submission blog post

### ISSUE THREAD

**Issue by arapov** [openssl/project#191]
When 3.1 is formally submitted to NIST, we need to write a blog post.

Very likely a copy/paste/fixup edit of: https://www.openssl.org/blog/blog/2021/09/22/OpenSSL3-fips-submission/

**Comment by paulidale** [comment]
I suggest that we should write the post **before** submission to NIST, so we can publish the blog immediate after submission.  People are going to notice the change in status relatively quickly.

**Comment by paulidale** [comment]
Blog post in: openssl/blog#54
