### ISSUE TITLE
Create CI target for building demos and unused reference code as aes_x86core.c

### ISSUE THREAD

**Issue by arapov** [openssl/project#195]
@mattcaswell: Should be a github action

**Comment by arapov** [comment]
@quarckster, @vavroch2010 looks like a task for infra...

**Comment by quarckster** [comment]
That needs to be elaborated.

**Comment by nhorman** [comment]
This seems like a duplicate https://github.com/openssl/openssl/pull/24047, @quarckster if you agree, please close

**Comment by quarckster** [comment]
@nhorman it looks like your PR implements what was asked in this issue. I consider it as completed. Thank you very much.
