### ISSUE TITLE
Fix VMS builds

### ISSUE THREAD

**Issue by levitte** [openssl/project#204]
There are some errors in the current VMS builds (master and 3.2) that need fixing, urgently.

**Comment by levitte** [comment]
I'll collect PRs here as they happen.  So far, they weren't specifically about VMS

**Comment by levitte** [comment]
- [X] openssl/openssl#21989 - Fixes two of the four failures
- [ ] test_quic_multistream (no PR yet) - probably caused by a hard-coded port number
- [ ] test_quic_tserver (no PR yet) - not yet analysed

**Comment by hlandau** [comment]
I am not actively working on this issue.

Based on the productivity of @nhorman's back and forth with @rsbeckerca on debugging NonStop one possibility might be to do low-latency back and forth between me and Richard to aid in debugging. I don't necessarily have the bandwidth to do this right now though.

**Comment by nhorman** [comment]
@levitte is there a way I can get access to a VMS image to install locally in a vm and test with?  I assume I can just go get an openvms eval license, but if theres a better approach that might be useful to know

**Comment by hlandau** [comment]
> @levitte is there a way I can get access to a VMS image to install locally in a vm and test with? I assume I can just go get an openvms eval license, but if theres a better approach that might be useful to know

I have filled out the OpenVMS x86-64 Community Licence request form something like 6+ months ago, though not on behalf of OpenSSL, and still have yet to hear back from them. Supposedly they are slowly dripping out community licences for x86-64 to avoid getting swamped with support requests.

It is a very easy form to fill in so you might want to at least get yourself in the queue: https://vmssoftware.com/community/community-license/

I think @levitte has access so he may be able to arrange something. He can definitely arrange access to some OpenVMS boxes.

**Comment by levitte** [comment]
I can install VMS for x86_64 on a VM, and actually planned for myself to do so...  but time.

Given this commentary, I can move that up my priority list.

**Comment by nhorman** [comment]
filled the form out, thanks!

**Comment by arapov** [comment]
Looks like this can be closed. @levitte  let me know if you have something else in mind.
