### ISSUE TITLE
QLOG logging infrastructure - impl - framework

### ISSUE THREAD

**Issue by hlandau** [openssl/project#210]

**Comment by hlandau** [comment]
Blocked on #279

**Comment by arapov** [comment]
@hlandau I believe the block can be removed. We must have this feature in master, although with a proper disclaimer. IIRC, we discussed this only at the WG call; it is important to communicate this to @openssl/otc and see if there are no objections.

**Comment by hlandau** [comment]
> @hlandau I believe the block can be removed. We must have this feature in master, although with a proper disclaimer. IIRC, we discussed this only at the WG call; it is important to communicate this to @openssl/otc and see if there are no objections.

My preferred route to do this is via https://github.com/openssl/general-policies/pull/59, and feedback there is still desired.

If we do not have the ability to make that happen, or make it happen rapidly enough, it's certainly true we can make this happen. Experimental features would be my preferred route. But there are some other options to manage the risk/instability.

**Comment by t-j-h** [comment]
This is not an experimental feature - it is a core feature that we need to have in the release and need to have it available. 
That the format might change isn't an issue in reality that would mean we have to put this in a special category and not have it available by default. It just needs to be made clear if the QLOG spec updates we will follow it.
Sharing stuff in QLOG format is a core QUIC stack feature in my view.

**Comment by hlandau** [comment]
If the format is changing then in my view it's the very definition of an experimental feature. "Not having it available by default" is the entire point of this.

"If the QLOG spec updates we will follow it" &mdash; this doesn't even implement the current draft version of the QLOG spec. It *deliberately* implements the prior draft version of the QLOG spec because that's the version currently supported by QVIS. In other words I chose to implement the version QVIS supports rather than the current state of the I-D.

It is correct that it is a question of how feature stability is communicated. That is the entire reason for the proposed policy.
