### ISSUE TITLE
Migrate Linux buildbot jobs to GHA

### ISSUE THREAD

**Issue by quarckster** [openssl/project#216]
As a part of efforts to unify CI, we want to migrate Buildbot jobs to GHA. A good start would be to move existing Linux jobs to GHA and run them in containers.

Acceptance criteria:
 * Migrate the following jobs to `os-zoo` workflow:
   * unix-centos8-x86_64
   * ~unix-debian10-arm64~
   * unix-debian10-x86_64
   * ~unix-debian11-arm64~
   * unix-debian11-x86_64
   * unix-fedora38-x86_64
   * unix-rockylinux8-x86_64
   * ~unix-ubuntu-aarch64~
   * unix-ubuntu2004-x86_64
 * Make it for branches: master, 3.1, 3.0, ~1.1.1~
 * Disable aforementioned jobs in the Buildbot

**Comment by t8m** [comment]
> * Make it for branches: master, 3.1, 3.0, 1.1.1

The OS-zoo workflow currently runs on schedule and only on the master branch. It can be changed to either run on schedule on all the branches, or on push to individual branches (then it needs to be merged to 3.1 and 3.0).

It does not make any sense to run it on 1.1.1 on the public repository because there will be no changes anymore there.

**Comment by paulidale** [comment]
Are ARM aarch64 hosts available in actions?

**Comment by t-j-h** [comment]
Part of the benefit of buildbot is the ability to run a test across a range of systems without the code having to be checked in - i.e. it can operate off a working tree.

**Comment by quarckster** [comment]
> Part of the benefit of buildbot is the ability to run a test across a range of systems without the code having to be checked in - i.e. it can operate off a working tree.

These kinds of tasks can stay on buildbot. Currently, upstream is tested on two CIs. It doesn't make sense to run the jobs that work with the tree on two different CIs. Upstream heavily uses GHA so it's logical to move all jobs there for better maintainability.

**Comment by paulidale** [comment]
We run an aarch64 build & test as part of the cross-compiles workflow using qemu and yes it's slow.
Build on PR and test on commit.

**Comment by t8m** [comment]
#17900 can be easily workarounded by having the aarch64 built with no-afalgeng.

**Comment by levitte** [comment]
> Part of the benefit of buildbot is the ability to run a test across a range of systems without the code having to be checked in - i.e. it can operate off a working tree.

Unfortunately, we haven't got that in place.  I did try, but there was something not working right.  Also, the `try` user interface is, quite frankly, pretty rubbish...  that's at least my impression from actually trying to use it.

With github, it's possible to enable actions on your personal forks, so simply pushing a branch will kick them into action.  That essentially fulfills the same purpose, and in a manner that's much easier to handle in my opinion.

**Comment by quarckster** [comment]
I paused workers the following workers in the Buildbot UI ossl-centos8-x86_64, ossl-debian10-x86_64, ossl-debian11-x86_64, ossl-fedora38-x86_64, ossl-macos11-x86_64, ossl-rockylinux8-x86_64, ossl-ubuntu2004-x86_64.
