### ISSUE TITLE
Add CPU report to workflows

### ISSUE THREAD

**Issue by quarckster** [openssl/project#227]
To analyze some CI failures we should know CPU model and its instructions.

Acceptance criteria:

* CPU report step is added into all jobs with `make test`
* CPU report includes CPU model and CPU instructions

**Comment by quarckster** [comment]
cc @t8m

**Comment by quarckster** [comment]
I couldn't find a cross-platform tool that shows the CPU instruction set. @t8m proposed using `openssl version -c` but its output is not human readable. I ended up using specific tools for each platform:
Linux - `/proc/cpuinfo`
MacOS - `sysctl machdep.cpu`
Windows - `Coreinfo.exe`

An example of usage is here https://github.com/quarckster/openssl/actions/runs/6336862270/job/17210782377

My only concern is that Coreinfo is not free software and requires EULA to be accepted.

**Comment by paulidale** [comment]
Human readable isn't critical IMO.  We should only occasionally need this information and the extra pain of looking up bit fields shouldn't be great.  Perhaps Windows builds could run `openssl version -c` which avoids the EULA concern.

**Comment by t8m** [comment]
Actually I would always run openssl version -c along with dumping cpuinfo.

**Comment by paulidale** [comment]
Both is good.  There have been suggestions about tests running with CPU features disabled (not sure if there are any yet).

**Comment by quarckster** [comment]
@t8m I want to run `openssl version -c` on Windows and wondering how it's built there. For Linux I have to specify `LD_LIBRARY_PATH` variable, do I need to do something similar for Windows?

**Comment by paulidale** [comment]
Run `./util/wrap.sh apps/openssl version -c` or equivalent

**Comment by paulidale** [comment]
The wrap script sets up everything required.

**Comment by quarckster** [comment]
On Windows I couldn't get `openssl version -c` working. The output of the command:

```
CPUINFO: N/A
```

Testing run https://github.com/quarckster/openssl/actions/runs/6362234488/job/17277141483

**Comment by quarckster** [comment]
> On Windows I couldn't get `openssl version -c` working. The output of the command:
> 
> ```
> CPUINFO: N/A
> ```
> 
> Testing run https://github.com/quarckster/openssl/actions/runs/6362234488/job/17277141483#step:10:195

I just checked other Windows runs and there is an output from `openssl version -c`. Looks like only in "minimal" job the output is `N/A`

**Comment by paulidale** [comment]
Minimal is probably skipping the command line app.

**Comment by t8m** [comment]
It's the no-asm build option. With that, there is no CPU-specific code and not cpuid invoked so there is nothing to report. It is correct.

**Comment by arapov** [comment]
given that it was merged.

**Comment by quarckster** [comment]
> given that it was merged.

I added the "Resolves" with the references to this issue into the PR but looks like it didn't work as expected.
