### ISSUE TITLE
DSA & X9.31 RSA no longer valid

### ISSUE THREAD

**Issue by paulidale** [openssl/project#242]
The [FIPS 140-3 IG C.K](https://csrc.nist.gov/csrc/media/Projects/cryptographic-module-validation-program/documents/fips%20140-3/FIPS%20140-3%20IG.pdf) mandates a transition to [FIPS 186-5](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-5.pdf) and [SP 800-186](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-186.pdf) by Feb 4 2024.

The upshot of this is DSA and X9.31 RSA are no longer valid for creating signatures, they will remain allow for legacy verification use.

**Comment by arapov** [comment]
dupe of #324
