### ISSUE TITLE
XOF with RSA-PSS and ECDSA

### ISSUE THREAD

**Issue by paulidale** [openssl/project#243]
[FIPS 140-3 IG C.K](https://csrc.nist.gov/csrc/media/Projects/cryptographic-module-validation-program/documents/fips%20140-3/FIPS%20140-3%20IG.pdf) notes that: _An approved Extendable-Output Function (XOF) specified in FIPS 202 is now approved within RSA-PSS and ECDSA; before this could only be an approved hash function (e.g., SHA2, SHA3)._

We should confirm that this is possible and that it works.

**Comment by slontis** [comment]
It doesnt currently work since there are oid tables for der.
NOTE for shake the PR I added related to fixed output sizes for SHAKE also apply here.

**Comment by arapov** [comment]
Dupe of #331
