### ISSUE TITLE
FIPS Indicators Requirements

### ISSUE THREAD

**Issue by paulidale** [openssl/project#245]
Figure out what and how we're going to process FIPS indicators.

**Comment by slontis** [comment]
There needs to be a technical discussion on how to approach this

**Comment by arapov** [comment]
Minutes snapshot from the OTC call today:
```
** FIPS indicators

Can we have a simple, non-granular FIPS indicator?
    Hugo's draft ideas: https://github.com/openssl/openssl/pull/23366

    Do we need the indicator to reflect usage of other
    non-FIPS providers?

OTC needs to form a viewpoint on what is compliant with the FIPS
indicator policy.

We need someone to come up with a proposal for how we comply
with the FIPS indicator requirements. This is *not* about API
design (if any) but the enumeration of the requirements and
how we justify our compliance with each to the lab.

OTC: Technical design of how the FIPS indicator will work is an OTC decision.

FIPS Indicator Issue: https://github.com/openssl/project/issues/245
```

**Comment by slontis** [comment]
Example security policy related to indicators
https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp4631.pdf#%5B%7B%22num%22%3A56%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C54%2C365%2C0%5D

**Comment by t8m** [comment]
@slontis is working on a design

**Comment by paulidale** [comment]
I've ideas about how to approach this.  The Red Hat solution is not ideal IMO.

**Comment by t8m** [comment]
openssl/openssl#23609

**Comment by t8m** [comment]
@openssl/otc AI everyone to read the PR https://github.com/openssl/openssl/pull/23609

**Comment by t8m** [comment]
Shane updated the document.

**Comment by t8m** [comment]
The PR for the requirements is in progress, we do not need to track this here. Closing.
