### ISSUE TITLE
Create README-QUIC.md pointing to QUIC documentation resources

### ISSUE THREAD

**Issue by hlandau** [openssl/project#251]
- Short document providing links to documentation resources to enable them to be easily found
- Similar to links found in alpha 1 blogpost
- Avoid creating a whole new way of writing documentation, this is about making the documentation easier to find

**Comment by mattcaswell** [comment]
Somewhere (either in this .md or in the guide) we need some "quick start" info on how to create a connection to a server, e.g. how do I connect to google/cloudflare using the OpenSSL QUIC implementation?

**Comment by arapov** [comment]
it should be small document with a list of links inside, where to find an information:
- (brief) what is quic, what's it good for? 
  - link to tutorial
- quick start from the comment above
  - this document or other (tutorial?)
- links to the demos
- links to the man page

the blog post on alpha1 is a good resource to get the links.

**Comment by arapov** [comment]
has been merged
