### ISSUE TITLE
QUIC server to support QUIC demo apps

### ISSUE THREAD

**Issue by jamuir** [openssl/project#261]
The QUIC demo applications under `demos/guide` point to `www.example.com`, but they fail because that server does not support the unusual protocol our client wants (http/1.0 over quic).  Using `www.cloudflare.com` does not work either.

When learning about QUIC, there is value in being able to communicate with a real server.

We should somehow allow the demos to talk with a real server (either by giving instructions about setting up a local server, or providing a remote server ourselves).

**Comment by jamuir** [comment]
We discussed this some in the stand-up today:

- we could provide a container image (to be run locally)
- we could run a server in our cloud infrastructure.

The options above would be temporary measures b/c a QUIC server will be added to OpenSSL post 3.2.  We could give instructions about running that server locally.

**Comment by mattcaswell** [comment]
One possibility is to point users as the quicserver utility that exists within the codebase. It was never intended for end user use and is not installed via "make install". But it was used to develop the demos:

From the root of the build tree:

````
$ cd util
$ ./quicserver
quicserver [-6][-trace] hostname port certfile keyfile
$ ./quicserver localhost 4443 ../test/certs/servercert.pem ../test/certs/serverkey.pem
````

**Comment by hlandau** [comment]
You can also try using the HTTP/3 demo, of course.

**Comment by arapov** [comment]
Fix the documentation to point to `./quicserver`.
