### ISSUE TITLE
fix openssl profile-picture transparency

### ISSUE THREAD

**Issue by jamuir** [openssl/project#262]
The profile picture for openssl displayed at https://github.com/openssl is semi transparent, and that causes it to look faded when displayed over top of a dark background; e.g.:

![openssl-profile-picture-dark-mode](https://github.com/openssl/project/assets/5332385/1f9beaef-1aa9-4c53-a383-7af73bf7efbd)

**Comment by jamuir** [comment]
I think we discussed this briefly during a stand-up at the begin of October, but I did not find a ticket for it.

**Comment by levitte** [comment]
I think there was talk of making a non-transparent jpg (assumed with white background) to replace this

**Comment by jamuir** [comment]
I have created two new image files in the following PR:

https://github.com/openssl/openssl/pull/22626

Someone who has permission to update the profile picture for the OpenSSL organization on GitHub will need to upload the new png image.

**Comment by jamuir** [comment]
The PR was merged, and Richard L updated the profile picture on both our public and internal GitHub org pages.

Thank-you, Richard.

![openssl-new-profile-picture-dark-mode](https://github.com/openssl/project/assets/5332385/eedafa62-169d-48da-b2e8-c87f86587de1)
