### ISSUE TITLE
Create a mailing list with all OpenSSL project participants.

### ISSUE THREAD

**Issue by arapov** [openssl/project#270]
> Side note: we should really have a common internal list where we have everyone that we consider "team". I've been playing with the idea of either [social@openssl.org](mailto:social@openssl.org) or [stuff@openssl.org](mailto:stuff@openssl.org).

Acceptance criteria:

- a new mailing list ~team@openssl.org~ alumni@openssl.org is created
- it includes people from contractors@openssl.org, omc@openssl.org

**Comment by arapov** [comment]
From @mattcaswell:
IMO we should not call any such list "team". The real "team" is very large and includes anyone who is involved with OpenSSL in any capacity. This is what openssl-project is for.

Historic note we used to have an [openssl-team@openssl.org](mailto:openssl-team@openssl.org) list (which had people on it from what is now called the OMC) - but it was dropped because of its exclusionary nature.

It is unclear to me what this new list is for. What traffic would go to it?

Just thinking of our value:

"We believe that our governance and output should be transparent and open."

**Comment by arapov** [comment]
From @quarckster:
Originally the intention was to make the announcements regarding our new OpenSSL Matrix server. After that, it became clear that [contractors@openssl.org](mailto:contractors@openssl.org) doesn't include all stakeholders. Therefore @levitte proposed to create a new list for such announcements. The question is who should be included.

**Comment by arapov** [comment]
From @hlandau:
friends@? alumni@?

WG + committers at least.

**Comment by quarckster** [comment]
Is it still relevant?

**Comment by t-j-h** [comment]
This can be closed. We have "staff@openssl.org" that reaches everyone including volunteers who are participating on the "internal" side of things.
