### ISSUE TITLE
Communicate 3.2 final release plans, blogpost announcing intended final release date

### ISSUE THREAD

**Issue by hlandau** [openssl/project#275]
This includes a blogpost announcing the date on which we intend to make the final release.

It is separate from the final release announcement blogpost.

**Comment by sapkkaj** [comment]
Hi have made the blog post here. I dont know the exact date that we wish to make the final release I just have 14th November as a placeholder atm. https://github.openssl.org/openssl/blog/pull/71

**Comment by sapkkaj** [comment]
I have created a new blog post announcing the release date, as well as encouraging people to test out the beta release. https://github.openssl.org/openssl/blog/pull/73
