### ISSUE TITLE
Improve addrev and/or api.openssl.org performance

### ISSUE THREAD

**Issue by hlandau** [openssl/project#277]
When `addrev` is used to merge a PR, `api.openssl.org` is used to query the CLA DB and committers DB. This process is repeated per reviewer per commit. It is however *absurdly* slow, to the point where if you want to merge a 30 commit PR it is basically a coffee break.

There are various options to fix this:

- Fix api.openssl.org so it isn't absurdly slow (Perl codebase)
- Stick an HTTP cache in front of api.openssl.org
- Modify addrev so it caches retrieved information locally after retrieving it for the first time (Perl codebase)

IMO we should consider doing several of these.

This is an infrastructure ticket &mdash; @vavroch2010 @quarckster @levitte

**Comment by levitte** [comment]
I've actually seen this as a feature that makes me slow down when I'm a bit hyper...  :wink:

I've thought of modifying addrev so it analyses all relevant commits commits and generates a commit-id indexed cache of trailers to be added, then use rebase to perform...

**Comment by levitte** [comment]
I can this ticket being divided into multiple tasks, i.e. => epic

**Comment by paulidale** [comment]
If you have access to omc/data, you can set some environment variables so it uses the persondb directly from there.  This makes it very fast.  Of course this won't help everyone and the clone of omc/data has to be kept up to date.

Caching and preloading are the proper fix.

**Comment by hlandau** [comment]
> If you have access to omc/data, you can set some environment variables so it uses the persondb directly from there. This makes it very fast. Of course this won't help everyone and the clone of omc/data has to be kept up to date.

I have tried this but have yet to successfully make this work.

**Comment by paulidale** [comment]
This is what I've got setup:
```
CLADB=/home/pauli/.../data/cladb.txt
PERSONDB=/home/pauli/.../data/persondb.yaml
```

**Comment by levitte** [comment]
> This is what I've got setup:
> 
> ```
> CLADB=/home/pauli/.../data/cladb.txt
> PERSONDB=/home/pauli/.../data/persondb.yaml
> ```

... or simply:

DATA=/whatever/.../data

However, you must also install QueryApp from omc-tools, as it contains the method for direct DB access.

**Comment by hlandau** [comment]
> However, you must also install QueryApp from omc-tools, as it contains the method for direct DB access.

Aah, this explains it.

For any OpenSSL committers who use NixOS, [this is a Nixpkgs package I wrote to package the tools](https://gist.github.com/hlandau/189646452245f4929df396b01971d3ba).

**Comment by arapov** [comment]
> > However, you must also install QueryApp from omc-tools, as it contains the method for direct DB access.
> 
> Aah, this explains it.
> 
> For any OpenSSL committers who use NixOS, [this is a Nixpkgs package I wrote to package the tools](https://gist.github.com/hlandau/189646452245f4929df396b01971d3ba).

minor change so that it is "friendly" with home-manager: https://github.com/arapov/evolution/commit/7056584dc1554f931f32caa1d27b9a37062292f4

**Comment by quarckster** [comment]
I packed `QueryApp` into a container image and used the FastCGI interface with nginx instead of Apache and CGI. I hope it will speed up the app.

https://github.openssl.org/sysadmin/images/pull/27/files

**Comment by quarckster** [comment]
https://api.openssl.org has migrated to GCP. Could someone please check the performance of the `addrev` script?

**Comment by t8m** [comment]
@quarckster Good work! The performance seems improved radically. IMO we can close this as done.
