### ISSUE TITLE
Providers Meeting: Users Track: Fetching provider algorithms

### ISSUE THREAD

**Issue by mattcaswell** [openssl/project#282]
Prepare slides/material for the "Fetching provider algorithms" section (Users track). Suggested content:

- property queries
- query language
- default property query vs explicit property queries
- library contexts
- Explicit vs implicit fetching
- Caching fetched algorithms for performance
- Feedback + Q&A

**Comment by t8m** [comment]
Slides: https://docs.google.com/presentation/d/1hpIHimeoJIegMhP0ycdQWtpFo8oNqLJ-uRgOmcuXAT4/edit#slide=id.g29990d6c7a7_0_29

**Comment by mattcaswell** [comment]
General note: There is no discussion on library contexts (although they are mentioned several times) - and that's not been included in my "overview" slides either so that is a gap. I think it would fit better in these slides (and the overview is already 48 slides long)

Slides 7/8/9: I'd suggest bolding, or otherwise distinguishing the title line in the table
Slides 7/8/9: Perhaps include some examples of algorithms of each type?
Slide 11: Typo: order order
Slide 15: s/these not containing/those not containing/

**Comment by t8m** [comment]
> Slides 7/8/9: Perhaps include some examples of algorithms of each type?

These tables are already big enough. As IMO the examples for most case are pretty obvious, I'll mention them during the presentation and added them to speaker notes. 

As for library contexts - I'll add slides for them
