### ISSUE TITLE
QUIC TXP: Investigate cause of incorrect use_explicit_len calculation

### ISSUE THREAD

**Issue by hlandau** [openssl/project#288]
Following on from https://github.com/openssl/openssl/pull/22662 which is a stopgap fix for https://github.com/openssl/openssl/issues/22658

Investigate why `use_explicit_len` is not defined correctly and fix.

We can leave the stopgap fix in afterwards as it adds robustness in the face of bugs.

**Comment by mattcaswell** [comment]
use_explicit_len looks like this at the moment:

````
        /* Choose between explicit or implicit length representations. */
        use_explicit_len = !((can_fill_payload || !could_have_following_chunk)
                             && !needs_padding_if_implicit);
````

so it only considers the current stream - the `could_have_following_chunk` value only looks at chunks in *this* stream.

**Comment by hlandau** [comment]
(responded in #22662)
