### ISSUE TITLE
Providers Meeting: Choose the platform and set the dates

### ISSUE THREAD

**Issue by arapov** [openssl/project#291]
Original comment from @mattcaswell:

I suggest splitting the meeting into two different tracks, to be run on different days. People can sign up to both tracks if they wish or just one. Track 1 will be targetted at provider users and track 2 will be targetted at provider authors.

I propose running this as a series of short presentations on a particular topic, followed by a feedback/Q&A session after each presentation. The final session will be an open forum for anyone to ask any questions or to give feedback that has not been captured anywhere else.

We will repeat each track twice once at 8am UTC and once at 4pm UTC - so there will be four sessions in total.

I envisage the user session lasting up to 2 hours and the author session lasting up to 2.5 hours

**Comment by arapov** [comment]
@sapkkaj above is subject to verify and adjust if needed.

**Comment by sapkkaj** [comment]
We will be using zoom webinars to host the providers meeting. Once we agree on dates for the meetings I will set the registration pages and links for the different tracks. I suggest doing one set the last week of November and the other set the following week.

**Comment by t8m** [comment]
I do not think we have enough time to finish both tracks by Nov 30. I'd propose first doing Track 1 in both timezones and then the same for Track 2

**Comment by mattcaswell** [comment]
It seems ambitious to me that we will be ready by 29th.

**Comment by sapkkaj** [comment]
Do you think we can be ready by December 6th, we can push it by a week and do what Tomas recommended, where we do track 1 in both time zones on December 6th and 7th, then we do Track 2 the next week on December 13th and 14th

**Comment by mattcaswell** [comment]
That sounds plausible.

**Comment by mattcaswell** [comment]
Oh....except I am on vacation 13th/14th/15th. Not sure if that is a show stopper.

**Comment by t8m** [comment]
I'd call it a showstopper. Are we sure we won't be able to complete the Track 1 before 29/30th Nov?

**Comment by t8m** [comment]
And then Track 2 by 6th/7th?

**Comment by mattcaswell** [comment]
> NA and EMEA compatible time zone - 5 pm CEST
> Asia and Australia compatible time zone - 8 am CEST

Just to be clear we're talking 1500 UTC and 0600 UTC right? CEST is for summer time which no one is using right now...
