### ISSUE TITLE
RSA e limited to odd numbers 2¹⁶ < e < 2²⁵⁶

### ISSUE THREAD

**Issue by paulidale** [openssl/project#306]
Lower limit likely enforced to some extent already.  Upper limit unlikely to be enforced.

Section 5.4 (e)

Needs a FIPS backward compatibility flag.

**Comment by slontis** [comment]
It already does this... 
/*
 * Check exponent is odd.
 * For FIPS also check the bit length is in the range [17..256]
 */
int ossl_rsa_check_public_exponent(const BIGNUM *e)
{
#ifdef FIPS_MODULE
    int bitlen;

    bitlen = BN_num_bits(e);
    return (BN_is_odd(e) && bitlen > 16 && bitlen < 257);
#else

**Comment by t8m** [comment]
Yep, closing this.
