### ISSUE TITLE
RSA minimum bit length now >= 2048, 1024 not allowed

### ISSUE THREAD

**Issue by paulidale** [openssl/project#307]
Need to enforce this in generation

Section 5.1

**Comment by slontis** [comment]
We use "Generation of Probable Primes with Conditions Based on Auxiliary
Probable Primes"

See FIPS 186-4 Section B.3.6 where the constraints were  nlen is neither 1024, 2048, or 3072

In FIPS 186-5 Section A.1.6 it is now nlen >= 2048

**Comment by slontis** [comment]
NOTE:
ossl_rsa_fips186_4_gen_prob_primes() already conforms due to other constraints..
i.e.
    /*
     * NOTE: SP800-131A Rev1 Disallows key lengths of < 2048 bits for RSA
     * Signature Generation and Key Agree/Transport.

**Comment by t8m** [comment]
So is this a non-issue?

**Comment by arapov** [comment]
Closed; Assumed Done;
