### ISSUE TITLE
Additional zeroization requirements on failure

### ISSUE THREAD

**Issue by paulidale** [openssl/project#312]
Stupid requirement, on failure leaks no information because none is returned.

Probably need to implement this nonetheless.

Section A.1.5

**Comment by slontis** [comment]
ossl_rsa_fips186_4_gen_prob_primes() Needs to at least clear rsa->p and rsa->q on error

**Comment by Sashan** [comment]
I've submitted PR https://github.com/openssl/openssl/pull/24358

However, I'm bit confused here. The task refers to section A.1.5 in FIPS-186-5. The section title reads as: _A.1.5 Generation of Probable Primes with Conditions Based on Auxiliary Provable Primes_ The function `ossl_rsa_fips186_4_gen_prob_primes()`  @slontis is referring to implements code covered by section `A.1.6` (B.3.6 in former FIPS-186-4) The section title reads as _Generation of Probable Primes with Conditions Based on Auxiliary Probable Primes_ This *probable* vs. *provable* seems as an oversigh to me. I could not find any code in openssl which refers to *provable* prime generation (section A.1.5). So my assumption her is the A.1.5 is typo and we should refer to A.1.6 here. Thanks for the clarification here.

The referred pull request does what @slontis is asking for.

**Comment by slontis** [comment]
It is a typo, and it doesnt matter if it is A.1.5 or A.1.6 (the requirement is still the same)..

**Comment by Sashan** [comment]
thanks for clarifying. there are still lots of new things I need to learn. and the inconsistency just caught my attention.

**Comment by mattcaswell** [comment]
openssl/openssl#24358 was merged. Is there anything left to do here, or can this be closed too?

**Comment by Sashan** [comment]
I think this can be closed now. If I'm wrong, then let it be re-opened.
