### ISSUE TITLE
Generation of Random Primes that are probably prime process steps updated

### ISSUE THREAD

**Issue by paulidale** [openssl/project#316]
Steps changed to account for:
- step 1 is an updated length check
- #315
- step 4.7 is different from 186-4.

We will need to do this (apart from #315)

**Comment by slontis** [comment]
I think this is not right..

We use "Generation of Probable Primes with Conditions Based on Auxiliary
Probable Primes"

The steps in FIPS 186-4 Section B.3.6 and FIPS 186-5 Section A.1.6 seem to be the same (except for step 1 which we already changed)

**Comment by t8m** [comment]
I agree with @slontis. Closing this.
