### ISSUE TITLE
An additional GCD condition in Lucas Probabilistic Primality Test

### ISSUE THREAD

**Issue by paulidale** [openssl/project#318]
Not relevant, we don't do Lucas tests.
The condition is GCD(C, ¼(1-D)) = 1
See B.5 for the method.

Section B.3.3 step 2

**Comment by slontis** [comment]
We would only need to implement Lucas if NIST does something silly (which they were suggesting at some point to increase the MR rounds to a high number). This can be closed for now.

**Comment by t8m** [comment]
+1, closing.
