### ISSUE TITLE
Compute a Probable Prime Factor Based on Auxiliary Primes inputs changed

### ISSUE THREAD

**Issue by paulidale** [openssl/project#338]
The inputs for this have changed, specifically the condition on the two primes.
Parameter c is new but optional
The condition in step 9 has been updated to i ≥ 20(nlen/2) from i≥5(nlen/2)

Section B.9

**Comment by slontis** [comment]
Nothing to do here.. We already changed the conditional step bound due to it causing intermittent key generation failures

**Comment by t8m** [comment]
+1 Closing
