### ISSUE TITLE
ECDSA mandates verification of domain parameters during generation and verification

### ISSUE THREAD

**Issue by paulidale** [openssl/project#342]
Checking the validity of the domain parameters is in SP 800-89 and SP 800-186 Appendix D.1.
Also the validity of Q needs to be checked as per D.1 of SP 800-186 when verifying a signature (6.4.2).

We appear to have some SP 800-89 support already but not obviously ECDSA.

This is mandatory.

Refer 6.2.2

**Comment by slontis** [comment]
Not sure on this one..
It seems to be speaking generally about what a verifier should do before using the key gen.. (In the same way that it does in SP800-56) i.e. Unless I see the implementation of keygen specifically list this as a step, it is the users responsibility to do the key check?

**Comment by t8m** [comment]
We also use only named curves in FIPS_MODULE - is there anything to verify then?

**Comment by arapov** [comment]
@t8m thinks it can be closed ;-)
