### ISSUE TITLE
Conference Event Calendar

### ISSUE THREAD

**Issue by sapkkaj** [openssl/project#367]
Create a conference calendar with conferences for q1 and q2 of 2024. Include prices to exhibit, cfp dates, and engineer availibility#367  [original issue](https://github.com/openssl/project/issues/367)

[Tracking Spreadsheet](https://docs.google.com/spreadsheets/d/17RgGVB4XaJkCyNHW646bhh0SUmV-NvD5O_S0eyRz3Js/edit#gid=0)

Note the spreadsheet includes conference list and also travel commitments list.

**Comment by Fitnesskrokodyl** [comment]
AI for everyone: 
- Review the list of conferences before 17trh Jan, next WG mtg 
- Feel free to nominate yourself (see bookmark travel tracking) 

@Fitnesskrokodyl Create AI for everyone to do this (separate issue for all to review, nominate themselves)

**Comment by Fitnesskrokodyl** [comment]
AI for everyone to review the conference list [Travel Plan 2024 AI](https://github.com/openssl/private/issues/216 )

**Comment by Fitnesskrokodyl** [comment]
We are tracking this further in [Travel Plan 2024 AI](https://github.com/openssl/private/issues/216) 
Tim is woking on providing more info in section H, I, J. - Separate AI ticket for Tim is to be created. 

@sapkkaj Can we close this ticket? Please  update let me know if not / close this ticket if yes.
