### ISSUE TITLE
Draft an OTC meeting recording strategy

### ISSUE THREAD

**Issue by hlandau** [openssl/project#389]
- we publish minutes, which list items discussed during the meeting, but are not necessarily exhaustive for someone who did not attend the meeting
- OTC strives for transparency, so video or audio recording would be desirable
- security issues need to be discussed privately, but might be disclosed after advisory is public
- making recordings publicly available (where?) might change the flow of the meetings, as attendees might be concerned about things that stay on record (discussions are generally light and informal, but public records might affect this).

**Comment by Fitnesskrokodyl** [comment]
Please move to OTC board.

**Comment by slontis** [comment]
This will need some sort of individual disclaimer notice... e.g. 

Any opinions expressed during this recording, are entirely personal opinions, and do not represent the views of any company that individuals may work for.

**Comment by t8m** [comment]
OTC: This is not going to be resolved in foreseeable future. Closing.
