### ISSUE TITLE
Performance testing environment for https://github.com/openssl/openssl/issues/17627

### ISSUE THREAD

**Issue by quarckster** [openssl/project#399]
Reproduce the environment that is described in the issue https://github.com/openssl/openssl/issues/17627. As the first step, we agreed to create three VMs with 16 dedicated vCPUs on our infrastructure.

**Comment by quarckster** [comment]
cc @mattcaswell

**Comment by mattcaswell** [comment]
VM 1: Needs to have an instance of the "angie" web server installed. In /etc/angie/http.d I have this file for the test:

````
server {
    listen       8088 default_server reuseport;
    server_name  _;

    access_log  off;

    location / {
        root   /usr/share/angie/html;
        index  index.html index.htm;
    }

    location /echo10 {
        echo "0123456789";
    }

    location /echo1k {
        echo_duplicate 100 "0123456789";
    }

    location /echo10k {
        echo_duplicate 1000 "0123456789";
    }

    location /echo100k {
        echo_duplicate 10_000 "0123456789";
    }
}
````

VM2: First, install the conf tarball at https://github.com/openssl/openssl/files/13840908/g3tiles.tar.gz. Then we need a source build of the version of OpenSSL under test (master/3.2/3.0/1.1.1). Also a build of "g3tiles". Note that cargo/rustc *must* be at least version 1.75


````
git clone https://github.com/bytedance/g3/
cd g3
export OPENSSL_LIB_DIR=/path/to/openssl/build/dir
export OPENSSL_INCLUDE_DIR=$OPENSSL_LIB_DIR/include
export LD_LIBRARY_PATH=$OPENSSL_LIB_DIR
cargo build -p g3tiles --release
#Confirm g3tiles is using the version of OpenSSL we previously built
ldd target/release/g3tiles
./target/release/g3tiles -c /path/to/conf/tarball/g3tiles/benchmark/main.yaml -G benchmark -v
````

VM3: Needs a build of OpenSSL 1.1.1. Also a build of "g3bench":

````
git clone https://github.com/bytedance/g3/
cd g3
export OPENSSL_LIB_DIR=/path/to/openssl/build/dir
export OPENSSL_INCLUDE_DIR=$OPENSSL_LIB_DIR/include
export LD_LIBRARY_PATH=$OPENSSL_LIB_DIR
cargo build -p g3bench --release
#Confirm g3bench is using the version of OpenSSL we previously built
ldd target/release/g3bench
````

To run the test we run the g3bench application as follows, adjusting the concurrency level (the `-c` param) as appropriate for the test. For each run I restarted `g3tiles`, to ensure we start from the same position each time.

````
./target/release/g3bench h1 https://<address of VM2>:9093/echo10k --tls-name bench.example.net --tls-no-verify --ok-status 200 --no-keepalive --tls-protocol tls1.3 --tls-ciphers TLS_AES_128_GCM_SHA256 -c 10 -t 30
````

For each version of OpenSSL, and for each concurrency level, we record the requests per second value reported by g3bench (after it has run for 30 seconds).

**Comment by mattcaswell** [comment]
Oh...in the conf tarball I also modified the benchmakr/server.d/openssl.yaml file to change the "addrs" line to point at the angie web server.

**Comment by quarckster** [comment]
I prepared three VMs on work.openssl.org
perf-test-1 -  with angie
perf-test-2 -  with OpenSSL master and g3
perf-test-3 -  with OpenSSL 1.1.1-stable and g3
All of them have user "matt" and your public ssh key.
I was able to build g3 tiles on perf-test-2 but on perf-test-3 I couldn't build OpenSSL 1.1.1

**Comment by quarckster** [comment]
@mattcaswell do you need anything else in this ticket?

**Comment by mattcaswell** [comment]
I still need the ARM based environment with 32 cores in order to progress this - but would like to discuss with @arapov to understand where pursuing this fits with other priorities. So keep this ticket for now.

**Comment by mattcaswell** [comment]
I have discussed this with @arapov. @quarckster please can you create the arm based environment needed, i..e as per the environments described above but with 32 ARM cores each.
