### ISSUE TITLE
ddd_demoes update, use of our QUIC API

### ISSUE THREAD

**Issue by arapov** [openssl/project#40]
~~A "hello world" demo.~~
~~Write a demo app that interoperates with another QUIC implementation.~~

ddd_demoes should be updated.
- must be moved to demoes directory and up to date
- check for best practices tls stuff

(we don't refer to any of these demoes from man pages)

**Comment by hlandau** [comment]
This is an alpha blocker because the DDD PR also contains functional changes to enable it. But it has been approved and should go in presently.
