### ISSUE TITLE
Bug/PR Wrangler

### ISSUE THREAD

**Issue by arapov** [openssl/project#402]
- [Wrangler Duties](https://github.openssl.org/omc/wg/wiki/Bug-PR-Wrangler-Duties-and-Roster)

**Roster**
- @nhorman 
- @levitte 
- @mattcaswell 
- @sashan
- @vdukhovni 
- @t8m

**Comment by t8m** [comment]
Why is this closed? Isn't this a recurring task?

**Comment by nhorman** [comment]
I'm duplicating this issue on a per-iteration basis so we have a history of who held the role previously
