### ISSUE TITLE
AI for all, FOSDEM - booth questions

### ISSUE THREAD

**Issue by Fitnesskrokodyl** [openssl/project#404]
Related to: https://github.com/openssl/private/issues/214 
**Deadline: 26th Jan, 2024** 
Summary: It is our first booth at a conference. We will distribute 300+ t-shirts, stickers. 
We do not want to hand over t-shirts just like that, but have a conversation and make the
t-shirt to be a bit deserved. 

Let´s ask people a question related to OpenSSL and give them t-shirt based on the conversation
we have / answer. 

[Fill your suggestions here](https://docs.google.com/document/d/16NEEvSjvyZRtImyCBM7mbf5oN-FDqX4-_c5rU1bDqrs/edit)

Note: The document with suggested questions will be reviewed by WG members to approve the suggestions. It will probably be recycled for future conferences, too. It is not specific to one event only. 

Thank you all in advance for your kind help with this! 
E.

**Comment by sapkkaj** [comment]
I am creating a landing page linked to a qr code - will send an email regarding what pages we want linked in the landing page.

**Comment by Fitnesskrokodyl** [comment]
@sapkkaj Kajal, would you please check on the list of questions we have so far nominated and let me know WDYT? I would like to ensure we have enough good questions and I need your opinion on this before I would assign any further AI to our team members. Thanks! E.

**Comment by t8m** [comment]
I'd say we have some good questions there already.

**Comment by sapkkaj** [comment]
> @sapkkaj Kajal, would you please check on the list of questions we have so far nominated and let me know WDYT? I would like to ensure we have enough good questions and I need your opinion on this before I would assign any further AI to our team members. Thanks! E.

I think we have a good list of questions to do our jeopardy at the booth. As they are all questions that also give us a good idea how people are using OpenSSL

**Comment by Fitnesskrokodyl** [comment]
@sapkkaj Thank you. I believe that I can close this ticket, we can use the questions we have and roll it from there. If no objections, I am closing it before the deadline.
