### ISSUE TITLE
HACS and Real World Crypto conferences

### ISSUE THREAD

**Issue by t8m** [openssl/project#430]

**Comment by t8m** [comment]
Nicola intends to attend RWC and RWCPQ conferences. He can represent the project at HACS as well.

We are happy for any OTC member to represent the project for the OTC at HACS or RWC.

Expense coverage request should be submitted to OMC in advance.

**Comment by hlandau** [comment]
Discussed on 2024-01-30:

We are happy for any regular OTC participant to represent the OTC
at HACS or RWC. Nicola is confirmed as attending RWC.

Anyone requiring expense coverage should email the OMC ahead of time.

We are comfortable with potentially having multiple people representing the
project.

Nicola is planning an extended visit to the OQS project.
They are interested in talking to an OTC member about project plans
regarding post-quantum cryptography.

We want to develop a post-quantum cryptography plan but have yet to
do so, therefore it makes little sense to try and represent our position.
However, opening a dialogue with them would be a good idea.

Both OTC and non-OTC groups should engage in dialogue.

Nicola will engage in discussion and form a list of topics which
can be the basis of future group meetings.

**Comment by arapov** [comment]
@arapov requested an update... stay tuned.

**Comment by arapov** [comment]
We didn't make it this time; obtaining the exception was impossible, although I ensured that we would be contacted directly and with sufficient advance notice before the next HACS event.
