### ISSUE TITLE
Determine preferred approach for TLS 1.3 integrity-only ciphersuites (CIPHER vs MD)

### ISSUE THREAD

**Issue by hlandau** [openssl/project#434]
Action item from discussion on 2024-01-30.

Should integrity-only algorithms be allowed to use EVP_CIPHER or should we require them to use EVP_MD and modify our TLS code to have a MAC-only path?

**Comment by t8m** [comment]
So we have these two options:
1. Implement artificial AEAD cipher NULL with HMAC for the TAG
Pros:
- no need to modify TLS-1.3 record layer, there will be only one codepath there
Cons:
- additional indirection causing (small?) performance penalty
- the ciphersuite might be mistakenly used outside of the TLS context in a place where confidentiality is needed
- needs modification of providers
2. Add MAC-only codepath to the TLS-1.3 record layer
Pros:
- no need to modify providers, it is possible to use even the 3.0 FIPS provider
- no artificial AEAD cipher added
Cons:
- two codepaths in the TLS-1.3 record layer

To me the choice is clear.

**Comment by hlandau** [comment]
I agree with option 2 here.

**Comment by t8m** [comment]
> What I think is that implementing 2 code paths may be too invasive

With the refactored record layer I do not expect it so.

**Comment by beldmit** [comment]
Quoting RFC9150:
```
As defined in [RFC8446], TLS 1.3 cipher suites denote the Authenticated Encryption with Associated Data (AEAD) algorithm for record protection and the hash algorithm to use with the HMAC-based Key Derivation Function (HKDF). The cipher suites provided by this document are defined in a similar way, but they use the HMAC authentication tag to model the AEAD interface, as only an HMAC is provided for record protection (without encryption).
```
So artificial AEAD looks more natural to me

**Comment by hlandau** [comment]
I don't think there is some intrinsic need to match the "document architecture" of the RFC. The RFC may have chosen to hack it in in that way but it doesn't mean we have to.

It's not an AEAD. It just isn't.

**Comment by beldmit** [comment]
OK. Taking into account that if we don't try to mimic the HMAC-only ciphersuites into AEAD, we don't have to change the public constants that may be problematic, I withdraw my concerns.

**Comment by mattcaswell** [comment]
My preferred option is (2)

**Comment by t8m** [comment]
**OTC: The consensus of OTC is that the implementation should just use EVP_MAC API directly from the TLS record layer.**
