### ISSUE TITLE
Identify possible ways to handle the various EVP_MAX...LENGTH macros

### ISSUE THREAD

**Issue by t8m** [openssl/project#435]
Action item from discussion on 2024-01-30.

We need to list these macros and how they are currently documented and applied in the code.

We need possible ways how to be able to change/discard them as future algorithms might need that.

**Comment by t-j-h** [comment]
ARIA_MAX_KEYS
BLOB_MAX_LENGTH
DTLS_MAX_VERSION
ERR_MAX_DATA_SIZE
EVP_CTRL_TLS1_1_MULTIBLOCK_MAX_BUFSIZE
EVP_MAX_AEAD_TAG_LENGTH
EVP_MAX_BLOCK_LENGTH
EVP_MAX_IV_LENGTH
EVP_MAX_KEY_LENGTH
EVP_MAX_MD_SIZE
HMAC_MAX_MD_CBLOCK
OPENSSL_DH_CHECK_MAX_MODULUS_BITS
OPENSSL_DH_MAX_MODULUS_BITS
OPENSSL_DSA_MAX_MODULUS_BITS
OPENSSL_ECC_MAX_FIELD_BITS
OPENSSL_MALLOC_MAX_NELEMS(type)
OPENSSL_RSA_MAX_MODULUS_BITS
OPENSSL_RSA_MAX_PUBEXP_BITS
OSSL_CMP_PKIFAILUREINFO_MAX_BIT_PATTERN
OSSL_HPKE_MAX_INFOLEN
OSSL_HPKE_MAX_PARMLEN
OSSL_HTTP_DEFAULT_MAX_LINE_LEN
OSSL_HTTP_DEFAULT_MAX_RESP_LEN
PSK_MAX_IDENTITY_LEN
PSK_MAX_PSK_LEN
RAND_POOL_MAX_LENGTH
RSA_PSS_SALTLEN_MAX_SIGN
SIPHASH_MAX_DIGEST_SIZE
SSL3_MAX_SSL_SESSION_ID_LENGTH
SSL_MAX_CERT_LIST_DEFAULT
SSL_MAX_KEY_ARG_LENGTH
SSL_MAX_MASTER_KEY_LENGTH
SSL_MAX_PIPELINES
SSL_MAX_SID_CTX_LENGTH
SSL_MAX_SSL_SESSION_ID_LENGTH
SSL_RT_MAX_CIPHER_BLOCK_SIZE
SSL_SESSION_CACHE_MAX_SIZE_DEFAULT
TLS_MAX_VERSION
TLS_MD_MAX_CONST_SIZE
TS_MAX_CLOCK_PRECISION_DIGITS
TS_MAX_STATUS_LENGTH
XTS_MAX_BLOCKS_PER_DATA_UNIT

**Comment by t8m** [comment]
One option to resolve the issue for various EVP MAX LENGTH values would be to add an OSSL_PARAM indicating the true MAX LENGTH property for a given algorithm implemented in a provider.

If the provider recorded that such OSSL_PARAM was queried, it could happily ignore the MAX LENGTH as set by the macro.

For some of the MAX LENGTH params it could be outright possible to ignore them if the API call has a length/size of the provided buffer argument - if the caller provided larger buffer than the MAX LENGTH constant value.

**Comment by t8m** [comment]
Pull request https://github.com/openssl/openssl/pull/23883

**Comment by t8m** [comment]
The design document was merged.
