### ISSUE TITLE
Benchmark for decoder performance (privkey)

### ISSUE THREAD

**Issue by hlandau** [openssl/project#454]
An existing test for this case exists here: https://github.com/openssl/openssl/issues/20286#issuecomment-1433229574

Specifically:
1) Augment the pemread.c test in the tools repo to decode different key types
2) Augment the pemread.c test in the tools repo to decode different file formats
3) Change the name of the test to reflect (1) and (2) above

**Comment by Sashan** [comment]
I've submitted two pull requests:
  - [#188](https://github.com/openssl/tools/pull/188) which makes Makefile more friendly for non-gnu OSes
  - [#189](https://github.com/openssl/tools/pull/189) which delivers the benchmark. I basically took an Akamai gist shared by Rich Saltz and convert it from C++ to C. Then I took a `main()` function from of `pemread.c` and blended both pieces to resulting `pkread.c` I hope this something we kind of expect.

**Comment by Sashan** [comment]
I've just finished reading notes: `Augment pemread.c ....` and realized this is not what we want. I've closed pull request and add those changes to existing pemread.c

**Comment by Sashan** [comment]
I've just submitted a new pull request:
https://github.com/openssl/tools/pull/191

hope it meets expectations. I got stuck for a while with DER glitch for certain keys. Although the issue is known for some time it was very new thing for me. It's described here:
https://github.com/openssl/openssl/issues/16479

**Comment by nhorman** [comment]
This is completed by https://github.com/openssl/tools/pull/184
