### ISSUE TITLE
Fix the failing CIFuzz CI issue

### ISSUE THREAD

**Issue by t8m** [openssl/project#463]
The build fails due to running out of storage space.

We need to do that as the CI is broken by this failure.

**Comment by hlandau** [comment]
We could split the fuzzers into two CI jobs arbitrarily.

**Comment by t8m** [comment]
It would actually make sense to just clone and build the pull request branch and not all of them in the CI job but that would require having the build script somehow recognize that it is running the CIFuzz run and not OSS Fuzz run.

BTW the issue automagically fixed itself now but we should do something with it anyway as the current approach is just wasting resources and also causes irrelevant CI failures on pull requests when the stable branches builds are broken.

**Comment by nhorman** [comment]
can we split the ci jobs in two, running the CIFuzz job only on push, and running a separate job on pull_request, in which this latter job builds the fuzzers using the procedure in the fuzz/README.md file, and manually executing them?

**Comment by t8m** [comment]
This has been fixed already.
