### ISSUE TITLE
Investigate address/ubsan stochastic failure

### ISSUE THREAD

**Issue by hlandau** [openssl/project#478]
We have been getting a stochastic failure in the sslapi test recently. Someone needs to investigate this and fix it.

https://github.com/openssl/openssl/actions/runs/8196377920/job/22416473221?pr=23584

**Comment by mattcaswell** [comment]
This will be fixed by https://github.com/openssl/openssl/pull/23705

**Comment by nhorman** [comment]
PRs are merged, this I think can be closed
