### ISSUE TITLE
DTLS 1.3 feature branch

### ISSUE THREAD

**Issue by fwh-dc** [openssl/project#479]
This is a request to create a feature branch for the DTLS 1.3 functionality.

Name: `feature/dtls-1.3`
Issue: https://github.com/openssl/openssl/issues/13900
Expected finish: September 2024
Resources: I am able to work on the feature as part of my job.

**Comment by mattcaswell** [comment]
This has been approved. I'll work to get this created (slightly complicated by the upcoming 3.3 alpha release)

**Comment by levitte** [comment]
I've created the branch, now waiting for it to show up on github.com.

**Comment by levitte** [comment]
`feature/dtls-1.3` is now in place, started from the current HEAD of `master`
