### ISSUE TITLE
Implement Attribute Certificates

### ISSUE THREAD

**Issue by nhorman** [openssl/project#520]
Implementation of Attribute Certificates, see:
https://datatracker.ietf.org/doc/html/rfc3281

Need to enter subtasks and specific outline of work to be done here
```[tasklist]
### Tasks
- [ ] https://github.com/openssl/openssl/pull/15857
```

**Comment by mattcaswell** [comment]
This is this PR:

https://github.com/openssl/openssl/pull/15857

**Comment by t8m** [comment]
Yes, the initial support (which is what IMO should be sufficient for 3.4) is already implemented in https://github.com/openssl/openssl/pull/15857. This PR just needs updates to retarget it to 3.4 and reviews.
