### ISSUE TITLE
windows on arm CPU

### ISSUE THREAD

**Issue by Sashan** [openssl/project#525]
while working on [#23312](https://github.com/openssl/openssl/issues/23312) I've noticed we don't build/test openssl on windows arm. I would like to have at least one WinARM host around to give it a try. thanks.

**Comment by quarckster** [comment]
Windows on ARM is an unadopted platform, I don't think it's a priority to work on this now. To add this platform to our CI we should revise our Platforms policy.

**Comment by Sashan** [comment]
I think we should close this one. It is related to https://github.com/openssl/openssl/pull/24137,
apparently no one else here cares about arm here.

**Comment by quarckster** [comment]
> apparently no one else here cares about arm here.

@Sashan It's not true we have Ubuntu ARM64 GitHub runner in the following workflows

https://github.com/openssl/openssl/blob/master/.github/workflows/ci.yml#L129
https://github.com/openssl/openssl/blob/master/.github/workflows/os-zoo.yml#L162
