### ISSUE TITLE
Implement relocatable binaries for windows installer

### ISSUE THREAD

**Issue by nhorman** [openssl/project#550]
Our OpenSSL build anchors several paths at build time using the OPENSSLDIR/ENGINESDIR/MODULESDIR variables (and subordonate paths based on them),which is unworkable as on windows, with an installer, the selection of the install location is separated from the build time selections.  We need to be able to select those paths at install time and have the openssl binaries read them at run time.  We should use registry keys to store these paths on a per-installation basis.

- [x] Modify the installer to add the appropriate environment variable  keys during install (see below)
- [x] Modify the installer to add the appropriate hklm variables that are read only to installer

Note: This is dependent on #129

**Comment by nhorman** [comment]
Currently OPENSSLDIR is used in the construction of the following variables/macros:
* X509_CERT_AREA - only used in construction of the default config path, and is overridden by OPENSSL_CONF env var
* X509_CERT_DIR - used bin by_store_ctrl_ex and is overridden by OPENSSL_CONF env var
* X509_CERT_FILE - default certificate file, overridden by SSL_CERT_FILE env var
* X509_PRIVATE_DIR - only used by X509_get_default_private_dir which is undocumented and deprecated
* CTLOG_FILE -  overridden by CTLOG_FILE env var

given this set of use cases I think it would be sufficient to simply store default values for these environment variables in the register for all users

**Comment by mattcaswell** [comment]
Other things to consider are MODULESDIR and ENGINESDIR

**Comment by nhorman** [comment]
agreed, I do need to deal with those, but they are fortunately likewise specify-able at run time with environment variables

**Comment by mattcaswell** [comment]
> agreed, I do need to deal with those, but they are fortunately likewise specify-able at run time with environment variables

Right - but if they are not specified they have a built-in default which should probably come from the registry

**Comment by nhorman** [comment]
Right, thats the interesting bit though.  As I'm reading about this, I've discovered that environment variables in windows are in fact just Registry keys.  specifically they are stored in:
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager/Evinronment
