### ISSUE TITLE
Modify ossl_init_thread_start api to support freeing thread data without per-key destructor

### ISSUE THREAD

**Issue by nhorman** [openssl/project#558]
#552 is meant to investigate manners in which ossl_init_thread_start deletes per thread data in an in-appropriate manner.  This task tracks the implementation of the output of that task.  To be updated when a consensus is reached there.  Current proposal is:

- [ ] ossl_init_thread_start should be cloned to ossl_init_thread_start_ex to accept an additional parameter *data, which holds a pointer to thread local data - cloning is to preserve (allbeit broken) ABI for existing providers
- [ ] THREAD_EVENT_HANDLER should be expanded to hold a pointer to (1) above
- [ ] OSSL_thread_stop_handler_fn should accept a second parameter data to pass (1) to the callback
- [ ] init_thread_stop should call (3) with the extra parameter stored in (2)

**Comment by t8m** [comment]
Should this be transferred to openssl/project?

**Comment by nhorman** [comment]
It certainly could be, but I'm not sure I see a significant value in doing so, unless there just some book keeping value there

**Comment by mattcaswell** [comment]
It does not belong in this repo IMO and should be transferred
