### ISSUE TITLE
Adapt curl usage of nghttp3 so it can use OpenSSL QUIC

### ISSUE THREAD

**Issue by arapov** [openssl/project#56]
- curl does most of http/3, but not all.
- nginx 
  - https://github.com/ngtcp2
  - https://github.com/ngtcp2/nghttp3
- shim layer? 

Depends on investigation task: openssl/project#28

**Comment by t8m** [comment]
curl already added OpenSSL QUIC with nghttp3 as a backend. https://github.com/curl/curl/blob/master/docs/HTTP3.md
