### ISSUE TITLE
provision the regular running of our benchmark suite on our performance infrastructure

### ISSUE THREAD

**Issue by nhorman** [openssl/project#569]
- [x] Complete #353 
- [x] Provision system with a cron job to on a daily basis, checkout openssl/openssl relevant branches (actively updated branches)
- [x] Checkout tools repository
- [x] Build each openssl branch
- [x] build perf tools
- [x] run each perf tool on each openssl branch
- [x] record results in a local db

**Comment by quarckster** [comment]
Everything is done from this task list. I created an ansible playbook which runs performance benchmarks on primary supported platforms. The playbook is executed every night and the results are stored in MySQL DB. Data is displayed in the Grafana dashboard and available for internal evaluation.

**Comment by quarckster** [comment]
Keep in mind that not all benchmarks are executed due to various issues in perftools. Also benchmarks are not executed on Windows platforms due to the build errors of the perftools.
