### ISSUE TITLE
Capture perf data for MacOSX 11 on aarch64

### ISSUE THREAD

**Issue by nhorman** [openssl/project#587]
As per the description in #577 record the requested perf programs output in the format specified:
|thread count| number of iterations | openssl 1.1.1 per operation avg usec | openssl 3.0.0 avg usec |  master usec| std deviation |
|----------------|----------------------------------|---------------------------------|--------------------|--------|-------|

And post results here and in #577

**Comment by Sashan** [comment]
## evp_fetch

|thread count| numder of iterations | openssl 1.1.1 per operation avg usec | 1.1,1 std dev | openssl 3.0.0 avg usec | 3.0 std dev |  master usec| master std dev |
|------------|----------------------|--------------------------------------|---------------|------------------------|-------------|-------------|----------------|
| 1  | 25 |   .049466 | 0       |   .049395 | 0       |   .049395 |       0 |
| 2  | 25 |   .181658 | .028442 |   .186425 | .021330 |   .187125 | .023937 |
| 4  | 25 |   .569140 | .013453 |   .564008 | .017972 |   .568851 | .019519 |
| 8  | 25 |  3.260318 | .024186 |  3.266021 | .033719 |  3.271420 | .089084 |
| 16 | 25 |  6.545183 | .043243 |  6.550112 | .056480 |  6.590782 | .024351 |
| 32 | 25 | 13.044723 | .121897 | 13.072840 | .108990 | 13.187136 | .061237 |
| 64 | 25 | 26.100791 | .243542 | 26.151476 | .239006 | 26.357182 | .118726 |

## handshake

|thread count| numder of iterations | openssl 1.1.1 per operation avg usec | 1.1,1 std dev | openssl 3.0.0 avg usec | 3.0 std dev |  master usec| master std dev |
|------------|----------------------|--------------------------------------|---------------|------------------------|-------------|-------------|----------------|
| 1  | 25 |   911.848860 |  5.188600 |   911.117324 |  4.946810 |   910.426376 |  1.566095 |
| 2  | 25 |   944.438756 |  1.311934 |   943.755288 |  1.250304 |   944.582020 |  1.560671 |
| 4  | 25 |   982.799904 |  2.198509 |   981.099748 |  1.582068 |   981.795552 |  2.060974 |
| 8  | 25 |  1526.479304 |  5.397742 |  1528.894572 |  5.786345 |  1528.331060 |  5.799978 |
| 16 | 25 |  3007.632844 | 18.132280 |  2999.483168 | 15.190420 |  3000.615976 | 16.221672 |
| 32 | 25 |  6087.440319 | 30.760805 |  6081.120678 | 22.903535 |  6085.188230 | 27.739315 |
| 64 | 25 | 12197.117999 | 58.423024 | 12177.647476 | 35.920488 | 12179.225894 | 56.777871 |

## newrawkey

|thread count| numder of iterations | openssl 1.1.1 per operation avg usec | 1.1,1 std dev | openssl 3.0.0 avg usec | 3.0 std dev |  master usec| master std dev |
|------------|----------------------|--------------------------------------|---------------|------------------------|-------------|-------------|----------------|
| 1  | 25 |  1.418051 |  .004690 |  1.417997 |  .003464 |  1.418156 |  .004582 |
| 2  | 25 |  1.602178 |  .017262 |  1.598755 |  .017291 |  1.594513 |  .019849 |
| 4  | 25 |  1.779955 |  .012083 |  1.794338 |  .017860 |  1.790084 |  .018384 |
| 8  | 25 |  5.990483 |  .136996 |  6.028847 |  .246517 |  5.950751 |  .058719 |
| 16 | 25 | 11.768306 |  .102274 | 11.796140 |  .095655 | 11.726293 |  .134096 |
| 32 | 25 | 23.511564 |  .705375 | 23.379650 |  .252285 | 23.269826 |  .425480 |
| 64 | 25 | 46.653415 | 1.283295 | 46.971691 | 1.217253 | 46.834433 | 1.176976 |

## providerdoall

|thread count| numder of iterations | openssl 1.1.1 per operation avg usec | 1.1,1 std dev | openssl 3.0.0 avg usec | 3.0 std dev |  master usec| master std dev |
|------------|----------------------|--------------------------------------|---------------|------------------------|-------------|-------------|----------------|
| 1  | 25 |   .128898 |  .008774 |   .128979 |  .008774 |   .135844 |  .033926 |
| 2  | 25 |   .374093 |  .007000 |   .374964 |  .007211 |   .374234 |  .007483 |
| 4  | 25 |   .729228 |  .031320 |   .723540 |  .021517 |   .722728 |  .018493 |
| 8  | 25 |  5.638986 |  .207275 |  5.626434 |  .322367 |  5.587891 |  .277209 |
| 16 | 25 | 10.790319 |  .294023 | 10.884892 |  .316355 | 10.751184 |  .360702 |
| 32 | 25 | 18.493702 |  .594960 | 18.179929 | 1.031047 | 18.458281 | 1.014042 |
| 64 | 25 | 30.131932 | 1.454044 | 30.596729 | 1.312773 | 30.299060 |  .979703 |

##  randbytes

|thread count| numder of iterations | openssl 1.1.1 per operation avg usec | 1.1,1 std dev | openssl 3.0.0 avg usec | 3.0 std dev |  master usec| master std dev |
|------------|----------------------|--------------------------------------|---------------|------------------------|-------------|-------------|----------------|
| 1  | 25 |   .216801 | .001000 |   .217004 |  .001000 |   .218706 |  .008660 |
| 2  | 25 |   .234834 | 0       |   .235160 | 0        |   .234943 | 0        |
| 4  | 25 |   .250987 | 0       |   .252030 |  .005291 |   .251960 |  .002236 |
| 8  | 25 |  2.433658 | .085498 |  2.465705 |  .051166 |  2.380805 |  .146314 |
| 16 | 25 |  4.741081 | .300188 |  4.765834 |  .204159 |  4.604995 |  .429748 |
| 32 | 25 |  9.336240 | .702869 |  9.167667 |  .775856 |  8.913727 | 1.119973 |
| 64 | 25 | 17.661488 | .752763 | 16.746504 | 1.238835 | 17.560095 |  .945263 |

## rsasign

|thread count| numder of iterations | openssl 1.1.1 per operation avg usec | 1.1,1 std dev | openssl 3.0.0 avg usec | 3.0 std dev |  master usec| master std dev |
|------------|----------------------|--------------------------------------|---------------|------------------------|-------------|-------------|----------------|
| 1  | 25 |  19.074177 |  .121511 |  19.054300 |  .075940 |  19.059218 |  .071070 |
| 2  | 25 |  19.839321 |  .030495 |  19.830565 |  .026381 |  19.827734 |  .025534 |
| 4  | 25 |  23.435290 |  .031843 |  23.427678 |  .035085 |  23.449187 |  .025573 |
| 8  | 25 |  57.931834 |  .154748 |  57.873998 |  .201514 |  57.893662 |  .191973 |
| 16 | 25 | 126.135418 | 1.366012 | 126.348671 |  .566804 | 126.109782 |  .447429 |
| 32 | 25 | 269.866240 | 1.036593 | 269.997878 |  .731162 | 269.080248 |  .925581 |
| 64 | 25 | 563.029310 | 2.387771 | 564.305246 | 2.464479 | 562.552917 | 1.648008 |
 
## rwlocks

|thread count| numder of iterations | openssl 1.1.1 per operation avg usec | 1.1,1 std dev | openssl 3.0.0 avg usec | 3.0 std dev |  master usec| master std dev |
|------------|----------------------|--------------------------------------|---------------|------------------------|-------------|-------------|----------------|
| 1  | 25 |  N/A     | N/A     | N/A      | N/A     |  N/A     | N/A     |
| 2  | 25 |  .805815 | .212840 |  .875984 | .162576 |  .866735 | .215708 |
| 4  | 25 |  .994696 | .034842 | 1.005254 | .038000 |  .999494 | .027604 |
| 8  | 25 | 1.028890 | .007348 | 1.021053 | .014422 | 1.024758 | .012206 |
| 16 | 25 | 1.006972 | .010392 | 1.007855 | .007280 | 1.010928 | .010723 |
| 32 | 25 | 1.002197 | .008185 | 1.001487 | .010295 | 1.002768 | .011401 |
| 64 | 25 |  .911493 | .017492 |  .915047 | .017663 |  .913520 | .017146 |

## sslnew

|thread count| numder of iterations | openssl 1.1.1 per operation avg usec | 1.1,1 std dev | openssl 3.0.0 avg usec | 3.0 std dev |  master usec| master std dev |
|------------|----------------------|--------------------------------------|---------------|------------------------|-------------|-------------|----------------|
| 1  | 25 |   2.216042 |  .033852 |   2.224269 |  .027640 |   2.220884 |  .032726 |
| 2  | 25 |   2.503392 |  .021260 |   2.505073 |  .022022 |   2.503458 |  .020371 |
| 4  | 25 |   2.760126 |  .012000 |   2.765772 |  .013190 |   2.767371 |  .012922 |
| 8  | 25 |  18.432344 |  .339555 |  18.357592 |  .320176 |  18.389023 |  .359855 |
| 16 | 25 |  31.325930 |  .592943 |  31.205395 |  .697129 |  31.140205 |  .626198 |
| 32 | 25 |  61.996547 | 1.252533 |  61.850975 | 1.281630 |  61.780426 | 1.204110 |
| 64 | 25 | 121.646430 | 2.779188 | 121.623818 | 1.983642 | 120.132782 | 3.516475 |

## x509storeissue

|thread count| numder of iterations | openssl 1.1.1 per operation avg usec | 1.1,1 std dev | openssl 3.0.0 avg usec | 3.0 std dev |  master usec| master std dev |
|------------|----------------------|--------------------------------------|---------------|------------------------|-------------|-------------|----------------|
| 1  | 25 |   1.937900 |  .012727 |   1.944871 |  .014966 |   1.939948  .007810 |
| 2  | 25 |   2.954056 |  .042320 |   2.949390 |  .046216 |   2.946560  .062112 |
| 4  | 25 |  14.089291 |  .081024 |  14.049656 |  .082571 |  14.137265  .066917 |
| 8  | 25 |  30.958311 |  .179555 |  30.922012 |  .245768 |  30.908682  .314062 |
| 16 | 25 |  63.158996 |  .687951 |  63.108937 |  .740734 |  62.848817  .650552 |
| 32 | 25 | 129.614242 | 2.019499 | 129.003771 | 1.756871 | 129.797136 1.620915 |
| 64 | 25 | 283.403874 | 3.622778 | 282.576409 | 3.591473 | 282.093752 2.642071 |

## pkeyread

### der dh

|thread count| numder of iterations | openssl 1.1.1 per operation avg usec | 1.1,1 std dev | openssl 3.0.0 avg usec | 3.0 std dev |  master usec| master std dev |
|------------|----------------------|--------------------------------------|---------------|------------------------|-------------|-------------|----------------|
| 1  | 25 |  1264.370312 |     .301041 |  1264.092396 |     .287504 |  1264.088032 |    .361841 |
| 2  | 25 |  1308.500676 |     .703764 |  1308.243396 |     .345710 |  1308.034216 |    .155280 |
| 4  | 25 |  1357.268808 |    1.361225 |  1356.482492 |     .479391 |  1356.602756 |    .620503 |
| 8  | 25 |  2056.414168 |    5.447975 |  2053.973892 |    3.846418 |  2059.676288 |  13.278682 |
| 16 | 25 |  4097.147368 |   10.934831 |  4091.930932 |   12.770557 |  4093.438512 |  10.245090 |
| 32 | 25 |  8132.059560 |  147.226028 |  8169.232456 |   52.802313 |  8189.464856 |  39.674322 |
| 64 | 25 | 13347.612236 | 1175.680502 | 13349.595139 | 1030.689219 | 13045.884764 | 847.909620 |

### der dhx

|thread count| numder of iterations | openssl 1.1.1 per operation avg usec | 1.1,1 std dev | openssl 3.0.0 avg usec | 3.0 std dev |  master usec| master std dev |
|------------|----------------------|--------------------------------------|---------------|------------------------|-------------|-------------|----------------|
| 1  | 25 |  238.641380 |    .572389 |  238.513784 |    .083934 |  238.469780 |    .072408 |
| 2  | 25 |  247.274088 |    .129112 |  247.372928 |    .162748 |  247.253024 |    .130038 |
| 4  | 25 |  257.484136 |    .663600 |  257.347432 |    .099136 |  257.460040 |    .374975 |
| 8  | 25 |  390.750164 |    .785012 |  390.941308 |   2.024995 |  390.992188 |    .915222 |
| 16 | 25 |  776.975756 |   6.898043 |  779.324060 |   3.901138 |  779.297260 |   3.755782 |
| 32 | 25 | 1543.760579 |  40.690589 | 1552.933650 |  34.607050 | 1562.133861 |  24.481788 |
| 64 | 25 | 2940.711589 | 249.662018 | 2862.877416 | 228.731575 | 2960.730946 | 267.752569 |

### der dsa

|thread count| numder of iterations | openssl 1.1.1 per operation avg usec | 1.1,1 std dev | openssl 3.0.0 avg usec | 3.0 std dev |  master usec| master std dev |
|------------|----------------------|--------------------------------------|---------------|------------------------|-------------|-------------|----------------|
| 1  | 25 |  245.596960 |    .147566 |  245.530208 |    .069785 |  245.513116 |    .058215 |
| 2  | 25 |  254.352552 |    .271898 |  254.329248 |    .237008 |  254.334972 |    .265789 |
| 4  | 25 |  264.838368 |    .299432 |  264.831448 |    .278551 |  264.892412 |    .342356 |
| 8  | 25 |  402.587692 |    .912694 |  402.126664 |    .622038 |  402.339300 |   1.280916 |
| 16 | 25 |  800.787348 |   5.485943 |  800.200320 |   6.194285 |  800.861764 |   5.423539 |
| 32 | 25 | 1613.878997 |  22.270369 | 1605.731653 |  44.098531 | 1613.449209 |  26.701968 |
| 64 | 25 | 3105.917276 | 193.597922 | 3131.520487 | 209.049864 | 3076.181102 | 153.700732 |

### der ec

|thread count| numder of iterations | openssl 1.1.1 per operation avg usec | 1.1,1 std dev | openssl 3.0.0 avg usec | 3.0 std dev |  master usec| master std dev |
|------------|----------------------|--------------------------------------|---------------|------------------------|-------------|-------------|----------------|
| 1  | 25 |  28.054040 |   .069756 |  28.031764 |   .058574 |  28.052676 |   .046711 |
| 2  | 25 |  29.642316 |   .085562 |  29.601992 |   .088073 |  29.603256 |   .107731 |
| 4  | 25 |  31.783372 |   .324879 |  31.761748 |   .237831 |  31.771176 |   .254491 |
| 8  | 25 |  50.614460 |   .808333 |  50.791052 |  1.100552 |  50.708716 |   .963248 |
| 16 | 25 | 100.989900 |  3.300173 | 101.101416 |  3.329386 | 100.225128 |  3.150589 |
| 32 | 25 | 214.224852 |  9.843023 | 215.572835 |  9.670034 | 216.241557 | 10.413203 |
| 64 | 25 | 599.724768 | 20.158453 | 603.603306 | 23.552909 | 604.153123 | 28.080227 |

### der rsa

|thread count| numder of iterations | openssl 1.1.1 per operation avg usec | 1.1,1 std dev | openssl 3.0.0 avg usec | 3.0 std dev |  master usec| master std dev |
|------------|----------------------|--------------------------------------|---------------|------------------------|-------------|-------------|----------------|
| 1  | 25 |  14.726980 |   .122804 |  14.679604 |   .042095 |  14.673752 |   .031224 |
| 2  | 25 |  16.138784 |   .111004 |  16.139952 |   .123951 |  16.149024 |   .122437 |
| 4  | 25 |  18.095684 |   .070135 |  18.091132 |   .091016 |  18.076384 |   .059648 |
| 8  | 25 |  33.620836 |   .617007 |  33.662628 |   .452807 |  33.888680 |   .701921 |
| 16 | 25 |  68.237260 |  1.600378 |  67.600836 |  1.055918 |  68.136272 |  2.072292 |
| 32 | 25 | 162.409864 |  5.392933 | 164.951094 |  6.115369 | 164.145511 |  7.042636 |
| 64 | 25 | 501.999073 | 38.161730 | 506.011737 | 40.517664 | 514.494229 | 37.892273 |

### der x25519

|thread count| numder of iterations | openssl 1.1.1 per operation avg usec | 1.1,1 std dev | openssl 3.0.0 avg usec | 3.0 std dev |  master usec| master std dev |
|------------|----------------------|--------------------------------------|---------------|------------------------|-------------|-------------|----------------|
| 1  | 25 |  32.133516 |   .031733 |  32.124900 |   .023853 |  32.149552 |   .052421 |
| 2  | 25 |  33.826936 |   .077097 |  33.838444 |   .062856 |  33.815848 |   .086856 |
| 4  | 25 |  36.285280 |   .380784 |  36.181872 |   .111283 |  36.193284 |   .127597 |
| 8  | 25 |  56.025888 |   .699425 |  55.653072 |   .576304 |  55.929836 |   .447738 |
| 16 | 25 | 110.818736 |  3.074088 | 111.630388 |  2.728015 | 112.142812 |  2.768634 |
| 32 | 25 | 240.444109 | 11.123973 | 243.306749 | 12.409048 | 235.864201 | 10.544137 |
| 64 | 25 | 560.864125 | 36.158216 | 574.762899 | 39.175991 | 579.492683 | 43.530543 |

### pem dh

|thread count| numder of iterations | openssl 1.1.1 per operation avg usec | 1.1,1 std dev | openssl 3.0.0 avg usec | 3.0 std dev |  master usec| master std dev |
|------------|----------------------|--------------------------------------|---------------|------------------------|-------------|-------------|----------------|
| 1  | 25 |  1283.854180 |   4.614246 |  1282.779776 |   .983430 |  1282.553128 |   .576377 |
| 2  | 25 |  1328.885476 |    .717599 |  1328.535572 |   .443229 |  1328.630800 |   .446949 |
| 4  | 25 |  1378.863180 |   2.237978 |  1377.260096 |   .538995 |  1377.355336 |   .563086 |
| 8  | 25 |  2092.100792 |   4.430872 |  2089.438660 |  3.651669 |  2089.485484 |  4.776507 |
| 16 | 25 |  4166.755564 |  12.136642 |  4164.328508 |  6.410249 |  4167.762200 |  8.079138 |
| 32 | 25 |  8366.856681 |  22.939762 |  8364.611849 | 15.841014 |  8359.642903 | 15.492820 |
| 64 | 25 | 16640.179101 | 112.756177 | 16674.393023 | 77.531246 | 16713.074676 | 75.160424 |

### pem dhx

|thread count| numder of iterations | openssl 1.1.1 per operation avg usec | 1.1,1 std dev | openssl 3.0.0 avg usec | 3.0 std dev |  master usec| master std dev |
|------------|----------------------|--------------------------------------|---------------|------------------------|-------------|-------------|----------------|
| 1  | 25 |  250.499496 |   .216970 |  250.384508 |    .129603 |  250.398752 |    .157911 |
| 2  | 25 |  261.079464 |   .236480 |  261.134084 |    .241768 |  261.134884 |    .204416 |
| 4  | 25 |  271.832260 |   .341779 |  271.812596 |    .365142 |  271.752464 |    .322546 |
| 8  | 25 |  416.242688 |   .810881 |  416.428284 |    .930266 |  416.924016 |   2.287967 |
| 16 | 25 |  834.628528 | 12.481058 |  830.464888 |  16.539378 |  829.159360 |  11.459755 |
| 32 | 25 | 1679.411593 | 25.775271 | 1689.958849 |  25.253616 | 1689.184165 |  21.930104 |
| 64 | 25 | 3458.665147 | 75.754834 | 3454.796529 | 100.583801 | 3422.760499 | 121.689516 |

### pem dsa

|thread count| numder of iterations | openssl 1.1.1 per operation avg usec | 1.1,1 std dev | openssl 3.0.0 avg usec | 3.0 std dev |  master usec| master std dev |
|------------|----------------------|--------------------------------------|---------------|------------------------|-------------|-------------|----------------|
| 1  | 25 |  258.716748 |   .140171 |  258.638732 |   .076889 |  258.607728 |    .083797 |
| 2  | 25 |  268.829612 |   .395156 |  268.736952 |   .301327 |  268.706600 |    .368180 |
| 4  | 25 |  279.786284 |   .596681 |  279.534188 |   .183945 |  279.563076 |    .257745 |
| 8  | 25 |  428.242412 |  1.908647 |  427.965448 |  1.456419 |  427.846476 |   1.343171 |
| 16 | 25 |  848.017292 |  6.910025 |  849.231896 |  6.072879 |  849.761588 |   4.635901 |
| 32 | 25 | 1710.997931 | 11.382099 | 1711.323598 | 15.865867 | 1711.141964 |  14.781298 |
| 64 | 25 | 3435.486972 | 93.685308 | 3435.140970 | 91.416678 | 3446.060758 | 101.915292 |

### pem ec

|thread count| numder of iterations | openssl 1.1.1 per operation avg usec | 1.1,1 std dev | openssl 3.0.0 avg usec | 3.0 std dev |  master usec| master std dev |
|------------|----------------------|--------------------------------------|---------------|------------------------|-------------|-------------|----------------|
| 1  | 25 |  36.944800 |   .093621 |  36.970324 |   .111525 |  37.015044 |   .275918 |
| 2  | 25 |  39.629524 |   .383915 |  39.653196 |   .381549 |  39.414064 |   .397548 |
| 4  | 25 |  42.376404 |   .238411 |  42.385996 |   .228586 |  42.401788 |   .270523 |
| 8  | 25 |  73.493660 |  1.331804 |  73.566252 |   .949912 |  72.908072 |  1.249297 |
| 16 | 25 | 143.101476 |  7.162012 | 145.109608 |  6.238464 | 144.724576 |  6.468096 |
| 32 | 25 | 304.716238 | 22.539293 | 303.320331 | 18.062877 | 309.315355 | 16.145899 |
| 64 | 25 | 628.822184 | 36.050369 | 633.823893 | 26.268673 | 627.181465 | 44.090998 |

### pem rsa

|thread count| numder of iterations | openssl 1.1.1 per operation avg usec | 1.1,1 std dev | openssl 3.0.0 avg usec | 3.0 std dev |  master usec| master std dev |
|------------|----------------------|--------------------------------------|---------------|------------------------|-------------|-------------|----------------|
| 1  | 25 |  33.920592 |   .177690 |  33.963188 |   .194146 |  33.917776 |   .089442 |
| 2  | 25 |  36.627284 |   .129007 |  36.635900 |   .160190 |  36.653820 |   .298427 |
| 4  | 25 |  39.696248 |   .119297 |  39.664084 |   .088746 |  39.693956 |   .136227 |
| 8  | 25 |  72.553784 |  1.247304 |  71.844380 |  1.921671 |  72.229368 |  1.513168 |
| 16 | 25 | 141.895152 |  8.633787 | 141.360956 |  9.137286 | 141.817288 |  7.945344 |
| 32 | 25 | 293.135998 | 32.766981 | 295.216233 | 31.173772 | 306.307120 | 26.263771 |
| 64 | 25 | 614.758570 | 45.059949 | 598.324944 | 64.181508 | 610.303494 | 31.606242 |

### pem x25519

|thread count| numder of iterations | openssl 1.1.1 per operation avg usec | 1.1,1 std dev | openssl 3.0.0 avg usec | 3.0 std dev |  master usec| master std dev |
|------------|----------------------|--------------------------------------|---------------|------------------------|-------------|-------------|----------------|
| 1  | 25 |  40.159952 |   .073471 |  40.166424 |   .126035 |  40.144712 |   .061717 |
| 2  | 25 |  42.497756 |   .092919 |  42.455692 |   .109644 |  42.457204 |   .101970 |
| 4  | 25 |  45.732932 |   .109352 |  45.684824 |   .105721 |  45.741980 |   .163545 |
| 8  | 25 |  76.423156 |   .858032 |  76.540624 |   .663803 |  76.493848 |  1.297228 |
| 16 | 25 | 154.289896 |  3.443249 | 154.924712 |  3.155477 | 154.131120 |  3.354591 |
| 32 | 25 | 333.476713 | 11.089122 | 337.298718 |  9.910165 | 337.605678 | 10.655921 |
| 64 | 25 | 648.889301 | 60.277735 | 671.480726 | 19.742436 | 653.214844 | 67.087303 |
