### ISSUE TITLE
3.4.0 Affirm Final Release criteria Met

### ISSUE THREAD

**Issue by nhorman** [openssl/project#603]
https://openssl-library.org/policies/technical/release-requirements/

As the release comes after the beta releases there is no need to repeat the stability requirements as those should be held already by the beta releases.

 All issues triaged as regressions on the development branch from which the release is to be done must have a milestone assigned. Regressions are considered from the previous stable release series.
 All issues or pull requests with the milestone for the release are closed.
 There are no outstanding untriaged Coverity issues.
 Coveralls coverage has not decreased overall from the previous release from the particular development branch.
 The CI must pass on the tip of the development branch before the release commits are added to the tree, including the daily CI builds.
 The tree must be frozen for at least 7 days. No changes apart from regression or security fixes should be merged during the freeze.
 For 2 days before the release there should be no changes to ensure the daily CI builds run on the development tree tip.

**Comment by t8m** [comment]
Done.
