### ISSUE TITLE
1st review for DTLS 1.3 PR DTLS 1.3: Place start of ClientHello correctly when calculating binder

### ISSUE THREAD

**Issue by nhorman** [openssl/project#621]
Preform review of the reference pull request https://github.com/openssl/openssl/pull/24426

If the review results in approval, please mark this issue as done.

If the review results in requested changes, please create a new issue on the task list in openssl/project#893 to track the need for a subsequent review after changes have been made, then mark this issue as done

**Comment by t8m** [comment]
This was already approved and merged.
