### ISSUE TITLE
Review Performance data from initial ubuntu/macosx and identify areas to improve

### ISSUE THREAD

**Issue by nhorman** [openssl/project#641]
Need to look a the performance data captured via issue #579 and potentially create tasks for improvement in the tracking epic

**Comment by Sashan** [comment]
[perf-plots.tgz](https://github.com/user-attachments/files/16975266/perf-plots.tgz)
the tar.gz file contains a shell script which generates barcharts from run-perf.pl output.

the master branch performs lot better than 3.0.
when comparing with 1.1.1 performance vary. Some tests are better some worse.
It also varies from platform to platform. This may suggest that test runs into
limits imposed by OS/platform itself. To analyze those cases we need to gather
profiling data to see where CPU cycles are spent.

**Comment by Sashan** [comment]
profile FreeBSD on x86 (https://github.com/openssl/project/issues/834)
profile FreeBSD on x86_64 (https://github.com/openssl/project/issues/835)
profile MacOS on x86 (https://github.com/openssl/project/issues/836)
profile Win x86 (https://github.com/openssl/project/issues/837)
profile Win x86_64 (https://github.com/openssl/project/issues/838)
profile debian 11 x86  (https://github.com/openssl/project/issues/839)
profile debian 11 x86_64  (https://github.com/openssl/project/issues/840)
profile Ubuntu 22.04 x86_64  (https://github.com/openssl/project/issues/841)

**Comment by Sashan** [comment]
please review the charts attached in this in `tar.gz` And also gnuplot script The script processes data produced by `run-perf.pl` script. The script already records average results for tests, so the variation in data should be minimized.

on some platforms some data point to some problem/glitch encountered when running the performance test. for example results for newrawkey test for 1.1.1 look really odd. I suggest to re-run the test first in cases like that.

Also x509storeissuer test performance varies platform to platform, the regression was spotted on just few of them 

I suggest to review generated .png files using `xv *`
