### ISSUE TITLE
write a performance test profiling the run time of EVP_PKEY_derive_set_peer

### ISSUE THREAD

**Issue by nhorman** [openssl/project#646]
Based on the performance reports in https://github.com/openssl/openssl/issues/21833 , we should create a perf test that measures the run time of EVP_PKEY_derive_set_peer in our perf tools repository.

It should be able to measure the performance on at least DH ffdhe2048, ECDH P-256, P-521, and X25519.

```[tasklist]
### Tasks
- [ ] write a performance applicaiton in the same style as our existing tools, which allows for an arbitrary number of threads to iteratively execute EVP_PKEY_derive_set_peer, and report the number of usec per call to the user
```

**Comment by andrewkdinh** [comment]
PR to resolve this issue is here: https://github.com/openssl/perftools/pull/4
