### ISSUE TITLE
Run the evp_pkey_derive_set_peer test and confirm performance regression from 1.1.1 to 3.0/master

### ISSUE THREAD

**Issue by nhorman** [openssl/project#647]
Using the evp_pkey_derive_set_peer test written in a prior tasks, execute in over multiple threads against both openssl 1.1.1, 3.0 and the master branch, reporting results here, noting any significant regressions

If there is a regression, identify root cause

**Comment by andrewkdinh** [comment]
Using https://openssl-library.org/performance.html as my source and just ubuntu-20.04-x86_64:

1.1.1 averages:

- all tests <1 ms

3.0 averages:

- evp_setpeer ec521: 82 ms
- evp_setpeer dh: 182 ms
- evp_setpeer x25519: <1 ms
- evp_setpeer ec256: <1 ms

master averages:

- all tests <1 ms

Between 1.1.1 and 3.0 there is a significant regression (for ec521 and DH), but looks like it was resolved between 3.0 and master. These results are pretty consistent across the other platforms tested.

> These numbers on master reflect the changes of the DH and ECDH key validation to use the quick test for parameters where it is sufficient (i.e., known safe primes such as the FFDHE primes and EC curves with cofactor 1)
> 
> So yeah, this call is not free as on 1.1.1 but IMO acceptable.

https://github.com/openssl/perftools/pull/4#issuecomment-2293135756

**Comment by t8m** [comment]
Yes, that confirms the fixes (in 3.4 and master branches).
