### ISSUE TITLE
Implement an abbreviated peer key validation in evp_pkey_derive_set_peer

### ISSUE THREAD

**Issue by nhorman** [openssl/project#648]
Based on the commentary in https://github.com/openssl/openssl/issues/21833 , it seems likely that the performance regression is due to an expensive validation operation which didn't exist in 1.1.1 (but needs to).  suggested performance improvement is to use an abbreviated check on prime curves, which are guaranteed to have properties needed to allow said abbreviated checks (see comment [here](https://github.com/openssl/openssl/issues/21833#issuecomment-1695412092)

```[tasklist]
### Tasks
- [ ] Modify EVP_PKEY_derive_set_peer[_ex] to do a quick check on prime curves, otherwise preform a full check
- [ ] rerun perf tests from prior issues in the tracking epic to confirm performance improvement
```

**Comment by nhorman** [comment]
Need to investigate how to separate prime field curves  from non prime fields curves and in what locations so as to determine when we can run abbreviated checks

**Comment by t8m** [comment]
I've created a PR that should fix this. Actually the distinguishing condition is whether the cofactor of the ec group is 1 or not.
https://github.com/openssl/openssl/pull/24816
