### ISSUE TITLE
Review 1 for Enable AES-XTS Optimization on Power platform

### ISSUE THREAD

**Issue by nhorman** [openssl/project#655]
It has been requiested that PR https://github.com/openssl/openssl/pull/24531 be integrated, and OTC has approved

Please review the PR, and either approve or request changes

If changes are requested leave this PR open
If approved, please close this PR

If we arrive at the end of the sprint, and more reviews are needed, please create them in the tracking epic

**Comment by t8m** [comment]
Reviewed
