### ISSUE TITLE
OpenSSL Application Performance Tunning (Aug 01)

### ISSUE THREAD

**Issue by t8m** [openssl/project#658]

**Comment by nhorman** [comment]
@t8m, I believe this is a task for your upcoming webinar, correct?

**Comment by t8m** [comment]
Oh yes. I completely forgot I promised this. Not sure when this should happen @sapkkaj ? I am on vacation 22-28th July so I'd have to prepare the presentation week before that if I should present it just at the end of July.

**Comment by nhorman** [comment]
July 30th is the scheduled date for this presentation, I can assign this to you for the next sprint so we don't over-schedule you

**Comment by t8m** [comment]
Abstract:

Secure communication is crucial, but it can slow down your app. This talk covers how to speed things using OpenSSL up. We'll look at tweaking your OpenSSL build time options and how you can reclaim some of the performance spent in the OpenSSL provider support. In the realm of TLS, you'll learn about session caching, configuring proper key exchanges, and choosing the right cipher suites. Real-life examples and benchmarks will show how these tweaks can make a big difference. Join us to learn how to keep your app both fast and secure!
