### ISSUE TITLE
Investigate QUIC Gaps and determine MVP remaining requirements

### ISSUE THREAD

**Issue by nhorman** [openssl/project#667]
Need to determine what our Gaps in QUIC Server are and what needs to be done for MVP.

I'm understanding that this is being done this sprint

output is a listing of issues/tasks to be completed to attain QUIC MVP.

barring this QUIC server MVP will be rejected from 3.4

**Comment by levitte** [comment]
I'm on trying to find the feasibility of our current QUIC server stuff (including the immediate poll PR) in terms of interoperability, with a focus on trying curl as a client.

Discoveries so far:

- `demos/quic/server` from the master branch builds fine.

  I built it like this (in my build directory):

  ``` console
  $ cc -I./include -I../master/include \
       -g -Wall -Wsign-compare \
       -o server ../master/demos/quic/server/server.c \
       -L. -lssl -lcrypto
  ```

  I'm running it like this (in the same build directory):

  ``` console
  $ ./util/wrap.pl ./server 8080 ../master/apps/server.pem  ../master/apps/server.pem
  ```
- Running `s_client` against that server works:

  ``` console
  $ ./util/wrap.pl apps/openssl s_client -quic -alpn ossltest -connect 127.0.0.1:8080
  ...
  ---
  hello
  closed
  ```

  The server just prints two lines:

  ```
  => Received connection
  => Finished with connection
  ```

- Curl:

  This was a bit of a challenge to build, 'cause oh so many choices.  I wanted to maximize the use of system libraries, so configured it to use OpenSSL libraries and NGHTTP3 (and yeah, I build with CMake):

  ``` console
  $ cmake -S . -B _build -DCMAKE_INSTALL_PREFIX=../_install -DUSE_OPENSSL_QUIC=1 -DUSE_NGHTTP3=1
  ...
  $ cmake --build _build
  ...
  $ cmake --install _build
  ```

  Running it against the server above looks like this:

  ``` console
  $ LD_LIBRARY_PATH=../_install/lib/ ../_install/bin/curl --http3-only https://127.0.0.1:8080
  curl: (7) error:8000006F:system library::Connection refused
  ```

  This made the server above die with this:

  ```
  => Received connection
  couldn't write on connection
  809B5B7D9F7F0000:error:0A0000EB:SSL routines:tls_handle_alpn:no application protocol:../master/ssl/statem/statem_srvr.c:2250:
  809B5B7D9F7F0000:error:0A00017E:SSL routines:ch_on_handshake_alert:quic protocol error:../master/ssl/quic/quic_channel.c:1098:QUIC error code: 0x178, reason: "handshake alert"
  809B5B7D9F7F0000:error:0A0000CF:SSL routines:expect_quic_as:protocol is shutdown:../master/ssl/quic/quic_impl.c:335:
  ```

  To be figured out...

**Comment by levitte** [comment]
The failing curl call is because it uses a different ALPN than "ossltest"...  of course

**Comment by t8m** [comment]
@levitte the demo quic server is not an http3 server. That means it cannot work with curl.

It is questionable whether a demo http3 server would be a requirement for MVP. From testing the interoperability standpoint probably yes as most of the clients we would probably be interested in for interop testing would be http3 clients.

**Comment by levitte** [comment]
I know it's not an http3 server.  But I can at least see if I get a connection...  and I did, as soon as I hacked demos/quic/server/server.c to also accept "\x02h3" for alpn.

**Comment by levitte** [comment]
But, regarding http3 server...  we do have a demo for an http3 *client* in the demos, using nghttp3 on top of our calls.  Shouldn't it be possible to make a corresponding server?

**Comment by levitte** [comment]
Related: openssl/openssl#24671

With that patch, curl does connect, just to fail in the http3 layer:

``` console
$ LD_LIBRARY_PATH=../_install/lib/ ../_install/bin/curl -v -k --http3-only https://127.0.0.1:8080
*   Trying 127.0.0.1:8080...
* Server certificate:
*  subject: CN=server.example
*  start date: Jan 14 22:29:46 2016 GMT
*  expire date: Jan 15 22:29:46 2116 GMT
*  issuer: CN=Root CA
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
*   Certificate level 0: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
* Connected to 127.0.0.1 (127.0.0.1) port 8080
* using HTTP/3
* [HTTP/3] [0] OPENED stream for https://127.0.0.1:8080/
* [HTTP/3] [0] [:method: GET]
* [HTTP/3] [0] [:scheme: https]
* [HTTP/3] [0] [:authority: 127.0.0.1:8080]
* [HTTP/3] [0] [:path: /]
* [HTTP/3] [0] [user-agent: curl/8.9.0-DEV]
* [HTTP/3] [0] [accept: */*]
> GET / HTTP/3
> Host: 127.0.0.1:8080
> User-Agent: curl/8.9.0-DEV
> Accept: */*
> 
* Request completely sent off
* HTTP/3 stream 0 reset by server
* Connection #0 to host 127.0.0.1 left intact
curl: (95) HTTP/3 stream 0 reset by server
```

**Comment by levitte** [comment]
What constitutes "gaps" was left unspoken, and needs to be defined.

From Matrix conversations (will be updated):

[@t8m]
> IMO the main gaps are this, a simple demo server [we have one /Richard], a documentation, and most importantly going through the RFC and checking the MUSTs relevant to the server and fixing any missing ones.

[@Sashan]
> one of the missing pieces is IP address validation and amplification mitigation.if I remember correctly.

**Comment by mattcaswell** [comment]
Gaps that I see at the moment:
- openssl/openssl#24257 needs to complete review and be merged
- openssl/openssl#24388 needs to complete review and be merged
- We need some form of http3 capable quic server in order to perform interoperability testing (the http3 support could be minimal/hard coded).
- We need to perform some interoperability testing against at least one (preferably more) other QUIC implementations. It isn't sufficient just to confirm there is a QUIC connection established - we'd need to do some multi-stream application data transfers too IMO.
- QUIC support needs to be added to s_server (this may or may not be the same server that we add http3 support to as mentioned above)
- We need to extend the OpenSSL guide tutorials section to include some content on writing a QUIC server
- We need a sweep through the QUIC documentation to confirm it is still accurate. In particular there are numerous places where we say that our QUIC support is client side only (e.g. see doc/man7/openssl-quic.pod)
- We should perform a detailed analysis of all MUSTs and SHOULDs in the RFC to confirm that we have done everything. This work might identify further as yet unknown gaps which would need to be completed before QUIC MVP is ready

**Comment by mattcaswell** [comment]
- The quic server demo needs to be updated to use immediate mode polling
- The interoperability testing should include immediate mode polling
- It's unclear to me to what extent anything needs to be done for https://github.com/openssl/project/issues/301. This needs to be investigated and a determination made
- Similarly https://github.com/openssl/project/issues/302 should be investigated and may need implementation
- We may need some additional fault injector tests (https://github.com/openssl/project/issues/386)

**Comment by mattcaswell** [comment]
- Rebase, review and merge the feature branch

**Comment by nhorman** [comment]
Thank you all, I think this issue can be closed.  I will take your output here, and based on your recommendation via email, will reject the feature from our 3.4 planning board, and begin tracking it for evaluation and inclusion in 3.5
