### ISSUE TITLE
Investigate the Current validity of the QUIC server integration CID management  issue that is currently outstanding

### ISSUE THREAD

**Issue by nhorman** [openssl/project#714]
Issue https://github.com/openssl/project/issues/301 is outstanding for QUIC server support, but contains no details, only dependent PR's.  Investigation is needed to determine what, if any, additional work needs to be done to complete that task.

This issue will possibly result in the creation of additional tasks in pursuit of the QUIC server feature
```[tasklist]
### Tasks
- [x] Review CID management code against RFC and determine if there are any gaps
```

**Comment by t8m** [comment]
The lcidm (Local Connection ID Manager) is already partially integrated.

From my initial review of the RFC requirements it looks that we might be able to postpone the integration of rcidm (Remote Connection ID Manager) if we won't support connection migration of clients by the MVP server.
