### ISSUE TITLE
Fix the date/time against the releases on the downloads pages

### ISSUE THREAD

**Issue by mattcaswell** [openssl/project#768]
The date and time against the various downloads on the downloads pages is based on the timestamp of the file.

To be useful it needs to be the date that the release was made. For more recent releases these two things are generally the same thing. But for any release prior to 25th October 2023 they aren't. Everything is set to "2023-Oct-25".

This isn't useful.

**Comment by t8m** [comment]
This seems to be fixed now. Interestingly enough we've lost some timestamps on previous website redesign as can be seen on https://openssl-library.org/source/old/0.9.x/index.html Also some old tarballs were lost. https://web.archive.org/web/20150815132414/http://openssl.org/source/old/0.9.x/
