### ISSUE TITLE
Need to determine why our coveralls coverage has large jitter run to run

### ISSUE THREAD

**Issue by nhorman** [openssl/project#788]
Need to investigate why our coveralls coverage has so much jitter and fix it

https://coveralls.io/openssl/openssl

**Comment by nhorman** [comment]
Some data to consider:

Coveralls doesn't seem to have the direct ability to chart coverage statistics, so I pulled the json data and generated these graphs:



![Image](https://github.com/user-attachments/assets/900f610b-939f-445e-9e5b-5927efcd9314)



![Image](https://github.com/user-attachments/assets/45042815-d7e6-4442-92ba-31e6942a73ae)



![Image](https://github.com/user-attachments/assets/fa763d4b-28b1-4cd2-ad2a-0bba67c5bcf9)

For reference March 13,2024 is when we branched openssl-3.3 (where the green line begins), and we tagged openssl-3.0.0 on April 9, 2024

Some observations:

1) The openssl-3.3 branch is relatively stable in its coverage between march 13 and april 9, likely owing to the very low number of patches that we insert during that time

2) we see significant jitter in both master and openssl-3.3 (up to 4 percentage points) after we unfreeze openssl-3.3

3) on both branches, an _upward_ spike in coverage, seems to correlate to a _downward_ spike in both lines covered and missed.  For instance, on may 19, the master branch spikes to 69% coverage.  this correlates to the report covering 93874 lines, and missing 40464 lines.  Comparatively the master branch typically covers approximately 140000 lines, and misses approximately 71000 lines.

Looking on or about the dates of that spike, we had one commit:
```
commit a192b2439c0207ce1b04ba6137329b68f9e23680
Author: Hongren Zheng <i@zenithal.me>
Date:   Thu May 16 16:41:25 2024 +0800

    fips provider: explicitly setup cpuid when initializing
```


Which is odd, as it seems that would only impact code paths that potentially take advantage of our accelerated assembly files, and we build the coverage report with no-asm

The coverage job builds our library as follows:
```
CC=gcc ./config --banner=Configured --debug --coverage no-asm enable-fips enable-rc5 enable-md2 enable-ssl3 enable-nextprotoneg enable-ssl3-method enable-weak-ssl-ciphers enable-zlib enable-ec_nistp_64_gcc_128 no-shared enable-buildtest-c++ enable-external-tests -DPEDANTIC -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION
```

I'm a bit confused as to why we build with FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION since we're not running the fuzzers.

I'll be interested to see what @t8m 's change to run tests serially does here. (https://github.com/openssl/openssl/pull/25105).  Given the innocuous changes above for an identified spike in coverage, this does feel somewhat like its a stochastic issue from thread interaction

**Comment by t8m** [comment]
> I'm a bit confused as to why we build with FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION since we're not running the fuzzers.

Yeah, that is a mistake in the configuration. Even -DPEDANTIC does not make much sense to me.

`no-shared` is also a little bit strange, but perhaps it is necessary.

**Comment by nhorman** [comment]
I assume no-shared was meant to work around some lcov issue, though you're right, its odd as gprof seems to record counts per object file

**Comment by nhorman** [comment]
a little more data:

![coverage_percent](https://github.com/user-attachments/assets/8149ff23-0f97-4f13-b76f-e60c37e75bc4)

Looking at all our active branches, coverage was actually quite stable for some time, but around the start of may things started to get really erratic.  Should look for some change there that may have triggered the behavior

**Comment by nhorman** [comment]
scripts used to generate these graphs:


[buildgpdata.txt](https://github.com/user-attachments/files/16549692/buildgpdata.txt)



[plot.txt](https://github.com/user-attachments/files/16549699/plot.txt)

**Comment by Sashan** [comment]
The scripts worked, thank you for them. I had to do minor tweaks to get them running on my system (OpenBSD)
```
--- /home/sashan/Downloads/buildgpdata.txt	Tue Aug 13 14:53:20 2024
+++ buildgpdata.sh	Tue Aug 13 16:40:15 2024
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
 #############################################################
 # Usage: ./buildgpdata.sh <branch name> <num pages>
@@ -17,7 +17,7 @@
 BRANCH=$1
 NUMPAGES=$2
 
-TOKEN=$(cat ~/.coverallstoken.txt)
+TOKEN=$(cat ~/work.openssl/.coveralls-token)
 
 rm -f $BRANCH.data
 
@@ -36,7 +36,7 @@
 for i in $(seq 0 1 $LENGTH)
 do
     UPDATE=$(jq -r --argjson idx $i '.[$idx].updated_at' $FETCHED_JSON)
-    FMTDATE=$(date -d "$UPDATE" +%y-%m-%d 2>/dev/null)
+    FMTDATE=$(date -j -f %Y-%m-%d +%y-%m-%d "$UPDATE"  2>/dev/null)
 
     CVPCT=$(jq -r --argjson idx $i '.[$idx].covered_percent' $FETCHED_JSON)
     CVLN=$(jq -r --argjson idx $i '.[$idx].covered_lines' $FETCHED_JSON)
@@ -46,7 +46,7 @@
 done
 
 # remove the wierd null ending that coveralls gives us
-head -n -1 $BRANCH.data > $BRANCH.data.tmp
+sed -e '$ d'  $BRANCH.data > $BRANCH.data.tmp
 
 # sort the data to be in date order
 sort -b -k1.1,1.2 $BRANCH.data.tmp > $BRANCH.data
```
and here are the tweaks for plot.sh
```
--- /home/sashan/Downloads/plot.txt	Tue Aug 13 14:53:24 2024
+++ plot.sh	Tue Aug 13 16:39:12 2024
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 ################################################################
 # Usage: ./plot.sh <branch name> [<branch name>] ...
@@ -28,7 +28,7 @@
 for i in $*
 do
     DATANAME=$i
-    DATAFILE=$DATANAME.data
+    DATAFILE=`pwd`/$DATANAME.data
     if [ "$FIRSTTIME" == "yes" ]
     then
         STARTDATE=$(head -n 1 $DATAFILE | awk -F',' '{print $1}')
@@ -49,7 +49,7 @@
 for i in $*
 do
     DATANAME=$i
-    DATAFILE=$DATANAME.data
+    DATAFILE=`pwd`/$DATANAME.data
     if [ "$FIRSTTIME" == "yes" ]
     then
         FIRSTTIME=no
@@ -67,7 +67,7 @@
 for i in $*
 do
     DATANAME=$i
-    DATAFILE=$DATANAME.data
+    DATAFILE=`pwd`/$DATANAME.data
     if [ "$FIRSTTIME" == "yes" ]
     then
         FIRSTTIME=no
@@ -85,7 +85,7 @@
 for i in $*
 do
     DATANAME=$i
-    DATAFILE=$DATANAME.data
+    DATAFILE=`pwd`/$DATANAME.data
     if [ "$FIRSTTIME" == "yes" ]
     then
         FIRSTTIME=no
```
The new charts confirm the jitter is gone. I will upload new charts on Monday next week when there will be more data and close the issue. Will also look at CI-job to try to figure out why parallel execution creates a jitter.

![Image](https://github.com/user-attachments/assets/573f4d49-2447-491d-84e1-ca34c28e984a)



![Image](https://github.com/user-attachments/assets/ad0ff736-2e6d-4d01-a3a7-0d318799ddc7)



![Image](https://github.com/user-attachments/assets/b9382cac-62f4-47cf-9025-c5982928bacd)



![Image](https://github.com/user-attachments/assets/48bc8c2c-b29f-4a3d-b2c7-11377665ecbe)

**Comment by Sashan** [comment]
New charts show no jitter.

![Image](https://github.com/user-attachments/assets/4131fec4-53fa-4000-ac52-43f5aed94b80)



![Image](https://github.com/user-attachments/assets/efa72ab8-8b92-4221-8c29-9440f953fe17)



![Image](https://github.com/user-attachments/assets/329e3b4c-f4ed-42fa-aabb-98d9351b6deb)



![Image](https://github.com/user-attachments/assets/d49c90c3-b29f-4700-a52d-0b2f73ff21de)

**Comment by nhorman** [comment]
agreed, looks like we can close this

**Comment by Sashan** [comment]
detailed charts.

![Image](https://github.com/user-attachments/assets/c6d7db15-8ee5-4495-9a27-1863030a97e4)



![Image](https://github.com/user-attachments/assets/2ed9c0fa-13a5-4fe6-86e9-bf1dda19c45c)



![Image](https://github.com/user-attachments/assets/cb0f7d30-15f2-487b-826b-ae84436b8a46)



![Image](https://github.com/user-attachments/assets/693b641d-6edb-4f8d-8435-4c2b56c6d53c)

closing as done.
