### ISSUE TITLE
Upload old openssl releases onto GitHub

### ISSUE THREAD

**Issue by quarckster** [openssl/project#826]
To reduce costs and maintenance burden of hosting old openssl releases they should be uploaded to github.com/openssl/openssl. I proposed to start with 3.0.0-3.0.6 versions to get the feedback. If there will no be negative feedback  I will upload remaining old releases.

**Comment by t8m** [comment]
Please hold on this. I want the OpenSSL Foundation board discuss this first.

**Comment by t8m** [comment]
BTW, could you please evaluate the exact costs involved? Also I do not see there can be any maintenance burden as the data is completely static as this is only about preexisting old releases. If there is any maintenance burden, please describe it exactly here.

**Comment by nhorman** [comment]
@t8m, just to offer some historical reference here, I don't think there was  a significant maintenance burden per-se, but there was  a very significant cost burden to hosting releases ourselves, in that we received many 1000's of downloads per day from various releases (likely due to automated build systems), that were impacting our hosting expenses

**Comment by levitte** [comment]
Those thousands, were they downloads of the latest releases (should be a surprise to no one) or on old releases (at the time of download)?

**Comment by t8m** [comment]
Yeah, but these 1000's of downloads were about recent releases, not the old ones.

**Comment by nhorman** [comment]
I think @quarckster and @vavroch2010 have site data that shows the specific breakdown, I honestly don't recall what the division was.  @quarckster do you have the download stats you can share here?

**Comment by vavroch2010** [comment]
Stats from google CDN logs https://docs.google.com/spreadsheets/d/1cZfMwnf36ly40Ju0SFQAPxvPtbUNPdU9YI65KfA7Ttw/edit?usp=sharing

**Comment by quarckster** [comment]
> BTW, could you please evaluate the exact costs involved?

Here you can find the report https://drive.google.com/file/d/1IXqfvll2vldbR0W5D25_AQf4IxdJT9ji/view?usp=sharing. Since June we started to redirect download links to GitHub and it's significantly reduced costs. We can completely get rid of this cost if we will redirect remaining links.

> Also I do not see there can be any maintenance burden

There is some maintenance burden in redirects configuration. Links for releases 3.0.7 and newer must be redirected. Despite on we stopped publishing new releases with URLs `https://openssl.org.source/...` we get complaints that release links are broken. This means I should add a new redirect for each new release or figure out a crazy regex which nobody including me will not understand in the future.

**Comment by levitte** [comment]
I had a look this morning, found the redirection stuff, and eh gods...  from that perspective, I get you.

On the other hand, github seems like a pretty crap archive of old stuff that wasn't released there first.

This has me wonder if it wouldn't be better with a separate archive site, not hosted in expensive places, and which doesn't even have to be fast (so what if downloads of a tarball from 2020 takes a long time?)...  we could even have it mirror any new release that we place on github, and could prune old releases from github, i.e. only keep something like a year's worth of releases there?

Redirection of old URLs could be simplified that way...  `https://openssl.org/source/old/*.tar.gz*` could be redirected to the archive site, while `https://openssl.org/source/*.tar.gz*` could be redirected to github.  Simple, clean, no need to keep track of what version is where.

**Comment by quarckster** [comment]
> On the other hand, github seems like a pretty crap archive of old stuff that wasn't released there first.

What does make you think like that? Except of limitation of release date changing which most people don't care I don't see any other "crap".

> his has me wonder if it wouldn't be better with a separate archive site, not hosted in expensive places, and which doesn't even have to be fast (so what if downloads of a tarball from 2020 takes a long time?)... we could even have it mirror any new release that we place on github, and could prune old releases from github, i.e. only keep something like a year's worth of releases there?

This will make maintenance even harder. I will need to take care one more provider in to addition to the GCP.

> Redirection of old URLs could be simplified that way... https://openssl.org/source/old/*.tar.gz* could be redirected to the archive site, while https://openssl.org/source/*.tar.gz* could be redirected to github. Simple, clean, no need to keep track of what version is where.

I don't think it will work. https://openssl.org/source/old/ includes 3.x versions as well.

**Comment by levitte** [comment]
> > On the other hand, github seems like a pretty crap archive of old stuff that wasn't released there first.
> 
> What does make you think like that? Except of limitation of release date changing which most people don't care I don't see any other "crap".

Because of the release date issue, the time line on the release page will be screwed up, the top releases there will be old stuff, etc.

So I hear you saying "nobody actually looks at the release page"...  I disagree, but then we're just gonna exchange points of view and get nowhere.  Do you have any data supporting such a claim?

> > Redirection of old URLs could be simplified that way... https://openssl.org/source/old/*.tar.gz* could be redirected to the archive site, while https://openssl.org/source/*.tar.gz* could be redirected to github. Simple, clean, no need to keep track of what version is where.
> 
> I don't think it will work. https://openssl.org/source/old/ includes 3.x versions as well.

Er, why wouldn't it work?  I did say this:

> > ... we could even have it (the archive site) mirror any new release that we place on github ...

Which would mean that an archive site would have copies of *everything* (which is what an archive does either way, yeah?).

**Comment by levitte** [comment]
> I will need to take care one more provider in to addition to the GCP.

You already take care of machinery other than GCP 😉 

But also, could an archive be cared for by someone else?

**Comment by quarckster** [comment]
I made a script which creates GitHub releases. It gets a list of tags and creates a release if the tag has a release tarball. Also it adds release notes from https://raw.githubusercontent.com/openssl/openssl/master/CHANGES.md. You can check it out in my GitHub fork https://github.com/quarckster/openssl/releases

**Comment by mattcaswell** [comment]
Looks good. One problem though is that the master CHANGES.md file can sometimes lag the CHANGES file for individual branches. So there is no entry for 3.1.6 yet in the master CHANGES.md file, but there is one in CHANGES.md file in the 3.1 branch itself.

**Comment by mattcaswell** [comment]
In fact actually, we stop updating the master one after there is a more recent release. So we stop updating the 3.1 timeline in CHANGES.md file once there is a 3.2 release. Otherwise you get lots of duplicate entries when the same changes are applied to multiple branches.

**Comment by quarckster** [comment]
@mattcaswell I see, for now I'm not going to update release notes for existing releases on GitHub. I wanted to demonstrate how old releases will look.

**Comment by t8m** [comment]
I would add that it basically means that newer patch releases won't have any CHANGELOG entries. I would recommend not adding any CHANGES.md entries to the releases for now.
If anything these should be from NEWS.md (or NEWS) files extracted from the released tarball (or from the git tree at the respective tag) and not from the master branch CHANGES.md.
I'd recommend using NEWS instead of CHANGES because the entries in CHANGES are too low-level and verbose.

**Comment by quarckster** [comment]
@t8m I addressed your comments and release notes are taken from NEWS.md or NEWS from the respective tag tree https://github.com/quarckster/openssl/releases
