### ISSUE TITLE
Address Clusterfuzz ssl_session_calculate_timeout UBSAN issue

### ISSUE THREAD

**Issue by nhorman** [openssl/project#831]
https://oss-fuzz.com/testcase-detail/5361798964903936

Looks like we tripped over a signed integer overflow calculating a timeout value in libssl.

need to identify the root cause and fix it.

**Comment by Sashan** [comment]
I think this got fixed via this PR https://github.com/openssl/openssl/pull/25239

looks like the fuzzer has not pulled the fresh sources yet. the fuzzer report refers to old code:
https://github.com/openssl/openssl/blob/9fe6e030b2400b7421e770bdc693354adf5186ee/ssl/ssl_sess.c#L67

this is current version in 3.1 branch:
https://github.com/openssl/openssl/blob/d08954dda23194812b303a8e2cf4749fef871d3d/ssl/ssl_sess.c#L56
