### ISSUE TITLE
oqs interop test failing in CI

### ISSUE THREAD

**Issue by t8m** [openssl/project#844]
```
External interop tests commencing
 Cloudflare:
  x25519_kyber768 @ oqsprovider
kex=X25519Kyber768Draft00
  x25519_kyber512 @ oqsprovider
/home/runner/work/openssl/openssl/oqs-provider/scripts/oqsprovider-externalinterop.sh: line 42: echo: write error: Broken pipe
../../util/wrap.pl sh ../../test/recipes/95-test_external_oqsprovider_data/oqsprovider.sh => 1
not ok 1 - running oqsprovider tests
# ------------------------------------------------------------------------------
#   Failed test 'running oqsprovider tests'
#   at test/recipes/95-test_external_oqsprovider.t line 27.
# Looks like you failed 1 test of 1.95-test_external_oqsprovider.t .. 
Dubious, test returned 1 (wstat 256, 0x100)
```

Please see:
https://github.com/openssl/openssl/actions/runs/10906210475/job/30266951906

**Comment by t8m** [comment]
@baentsch Could you please look into this?

**Comment by baentsch** [comment]
@t8m , sure. Problem is that the external CF server changed its behaviour at that port (not running x25519-kyber any more but x25519-mlkem). This will be automatically corrected once the next oqsprovider release comes along doing the same change. But that's 1-3 weeks away as the OQS colleague implementing that is at ICMC...

Is that sufficient or should we do something to fix this faster? The only short-term thing I can think of is removing the test, i.e. either the whole oqsprovider test or a patch within openssl to facilitate that for now (need to check how). Any preference on your side?

**Comment by t8m** [comment]
I've merged the urgent CI fix but let's keep this issue open until the proper fix is merged.

**Comment by t8m** [comment]
@baentsch Isn't this done already?

**Comment by baentsch** [comment]
> @baentsch Isn't this done already?

Nope. Only a workaround. New `oqsprovider` release has only recently been done. Will do PR to fix this for good this week.

**Comment by baentsch** [comment]
See https://github.com/openssl/openssl/pull/25702

**Comment by vavroch2010** [comment]
Fixed
