### ISSUE TITLE
feature branch: feature/acert-cli

### ISSUE THREAD

**Issue by JonathanWilbur** [openssl/project#845]
Feature Branch Name: `feature/acert-cli`
Estimated Time to Completion: End of year 2024 (The code was already written; it just needs review)

There is currently no issue for this, but I can create one if requested. This feature-branch was requested by OpenSSL maintainers as a result of this PR: https://github.com/openssl/openssl/pull/25441.

I will re-iterate my opinion that we should not actually create a feature-branch for this, which I stated [here](https://github.com/openssl/openssl/pull/25441#issuecomment-2355991846):

> Actually, I take that back. I know I am outnumbered here, but I don't think this should be in a feature branch at all. This PR (which is not really that big overall), can be split into several smaller PRs already, each of which are individually useful, and they could be merged in any any order. I could create a PR for a CLI that supports no signing and verification and only printing, or I could create a PR that supports signing and verifying attribute certificates with no CLI, and even these can be broken down further into useful atoms.
>
> The overhead of repeatedly having to rebase and the possibility of these changes not making it into 3.5.0 because they are collectively only 90% done does not sound worth it to me.
>
> But that is just a point made about the technical usefulness of a feature branch. If you still want a feature branch as an administrative formality, I will still do whatever you want.

**Comment by JonathanWilbur** [comment]
@t-j-h Hello, I believe I am blocked on doing this work on there being a feature branch. Can one be created for this?

**Comment by t8m** [comment]
+1 to create the branch.

**Comment by t8m** [comment]
@t-j-h could you please ack it formally here?

**Comment by JonathanWilbur** [comment]
Hello @t-j-h sorry to bother you, but I figured I would bump, since 3.4.0 is released now, and I figured you might have been busy with that.

**Comment by arapov** [comment]
ACK for the feature branch.

**Comment by t8m** [comment]
feature/acert-cli branch was created.
