### ISSUE TITLE
Request for Feature branch for HSS/LMS

### ISSUE THREAD

**Issue by slontis** [openssl/project#846]
branch: feature/hss
PR ref:  openssl/openssl#22171
PR design: openssl/openssl#22357

This is a simple reference implementation of RFC 8554 that conforms to https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-208.pdf.

Most of the work is done, the PR mainly needs to be broken up into smaller reviewable parts.
I will continue work on this until the PR is moved to the feature branch.

**Comment by nhorman** [comment]
OTC: Can we approve this feature branch?

**Comment by t-j-h** [comment]
It is not an OTC thing to approve.

+1 from the corporation for this feature branch

**Comment by mattcaswell** [comment]
+1

**Comment by mattcaswell** [comment]
FYI: the feature branch approval policy says this request should have been created in the openssl/project repo.

**Comment by nhorman** [comment]
@mattcaswell shall we transfer this issue to project?

**Comment by t8m** [comment]
Transferred

**Comment by mattcaswell** [comment]
The "feature/hss" branch has been created.

**Comment by slontis** [comment]
Thanks @mattcaswell
Should I be able to see this in https://github.com/openssl/openssl/branches/all ?

**Comment by mattcaswell** [comment]
> Should I be able to see this in https://github.com/openssl/openssl/branches/all ?

Yes. I see it? Creating the branch might not have triggered it to be mirrored on github. So (possibly) it might not have been visible for a while until someone pushed something. Anyway its definitely visible now:

https://github.com/openssl/openssl/tree/feature/hss

**Comment by slontis** [comment]
Can see it now using the same method as before when it wasnt visible..
Thanks.
