### ISSUE TITLE
Release publishing workflow in fork

### ISSUE THREAD

**Issue by quarckster** [openssl/project#855]
Before changing CI of the main `openssl` repo release publishing automation must be tested on a fork.

Acceptance criteria

- Release publishing workflow  is created in https://github.com/quarckster/openssl-fork
- Workflow creates a draft release on a tag
- ~~Draft release contains release notes from NEWS.md~~
- Draft release contains source code tarball, pgp signature, sha1 and sha256 hash sums

**Comment by quarckster** [comment]
I setup a self-hosted runner to prepare release assets and create a GitHub release. Here is the [workflow](https://github.com/quarckster/openssl-fork/blob/master/.github/workflows/make-release.yml), [job logs](https://github.com/quarckster/openssl-fork/actions/runs/11272841206/job/31348602956) and the [release](https://github.com/quarckster/openssl-fork/releases/tag/openssl-3.9.9). The GitHub release is created as a draft and must be published manually.

**Comment by nhorman** [comment]
The workflow generally looks ok to me, though based on the release process:
https://github.com/openssl/tools/blob/8f8e9f7781b9aa900dd979833714e9cb72749db3/HOWTO-stage-a-release.md?plain=1#L1
We still need to wrap this in some manual steps.  Notably, 
we need to do what the stage-release.sh script does (update copyright year, update the version, etc)
we need to re-update the version after the release is tagged

Were those purposely left out of the workflow (assuming that manual work for that would be done outside the workflow)?

**Comment by quarckster** [comment]
Yeah, I decided to start with the end. This workflow can be integrated with the current release routine. Automating release staging is out of scope of this task, but it's a part of #811.
