### ISSUE TITLE
Review QUIC documentation man3 pods to ensure it is still accurate

### ISSUE THREAD

**Issue by nhorman** [openssl/project#870]
Review pods for references to QUIC, and for any relevant reference, ensure that the documentation matches the code behavior.  Open tasks for any corrections that need to be made.

@vdukhovni  to generate list of docs to verify

**Comment by Sashan** [comment]
I still think we should find a way to update documentation where we talk about default stream mode and multistream mode. We should introduce implicit stream mode and explicit stream mode here. Then we can add some more clarification into a HISTORY section in openssl-quic manpage where we can clarify on history. In terms of related API changes in header files new constants can be introduced as aliases of existing constants. They can co-exist.

**Comment by vavroch2010** [comment]
Revied
