### ISSUE TITLE
QUIC: Endpoints MUST NOT send a TLS KeyUpdate message.

### ISSUE THREAD

**Issue by nhorman** [openssl/project#898]
This is a missing MUST item from the spreadsheet here:
https://docs.google.com/spreadsheets/d/1is0eRNrmNwzqcCTmTPYJwC3fswpYpqmY87-5CylraLc/edit?gid=1067533579#gid=1067533579

Need to determine if this is still missing, and if it is, correct it

Investigate and if work required create another issue with description what needs to be done

**Comment by nhorman** [comment]
SSL_key_update redirects to ossl_quic_key_update, which never sends  a KeyUpdate record in the TLS data of a frame, so I think this requirement is met from the standpoint of the RFC

**Comment by t8m** [comment]
I reviewed the code and I agree. We will never send a TLS KeyUpdate message from a QUIC SSL.
