### ISSUE TITLE
Feature branch request for EVP_SKEY implementation

### ISSUE THREAD

**Issue by beldmit** [openssl/project#908]
According to https://openssl-library.org/policies/general/feature-branch-approval-policy/ I request a feature branch to implement usage of opaque objects as symmetric keys.

Proposed name: feature/evp_skey
A link to an issue describing the requested feature: https://github.com/openssl/openssl/pull/21573 is a design document I'm going to implement. 
ETA: 2025Q1

CC: @simo5, @neverpanic

**Comment by beldmit** [comment]
@openssl/corporation-members I want to draw you attention that the technical policy https://openssl-library.org/policies/general/feature-branch-approval-policy/ relies on OMC and so needs to be updated.

**Comment by t-j-h** [comment]
The policy does include four items that are expected (but we haven't been checking these to date):

- [x] The name of the feature branch requested in the form of feature/<name>
- [x] A link to an issue describing the requested feature that will be developed on the branch
- [x] An estimate of when the work on the feature is expected to be complete
- [x] Whether there are any known resources being made available to work on the feature

I'm assuming that @beldmit is the known resource.

On that basis +1 from the Corporation (waiting on Foundation)

The expectations is that multiple people are going to work on items and this will be a phased development and there will be some "challenges" along the way (some of which can be seen in the comments on the design approach document).

**Comment by mattcaswell** [comment]
> On that basis +1 from the Foundation

I'm going to read that as +1 from the Corporation :-)

**Comment by mattcaswell** [comment]
+1 from the Foundation too.

**Comment by mattcaswell** [comment]
The feature/evp_skey branch has been created.
