### ISSUE TITLE
Change the default cipher for req, cms and smime apps

### ISSUE THREAD

**Issue by t8m** [openssl/project#909]
After openssl/openssl#25776 is fixed (i.e. -cipher is implemented for `req`) we should change the default for req, cms and smime apps from 3des to aes-256.

**Comment by adimail** [comment]
Hi @t8m,

The prerequisite issue is now fixed. Would it be okay if I work on changing the default ciphers?

Should I wait for my previous PR to be merged first, or would it be fine to open a new PR for this change now?

Thanks!

**Comment by t8m** [comment]
> Should I wait for my previous PR to be merged first, or would it be fine to open a new PR for this change now?

I would wait for it being merged.

**Comment by t8m** [comment]
Ah, it was merged already, so you can go ahead with that PR.
