### ISSUE TITLE
validation token is currently naive

### ISSUE THREAD

**Issue by Sashan** [openssl/project#912]
This issue refers to draft PR [#25842](https://github.com/openssl/openssl/pull/25842). The prototype uses simple `openssltoken` string as a validation token. This is not sufficient to provide protection against spoofing. The token needs to serve as proof it comes from server and it must be impossible (computationally expensive) to anyone to generate valid token. I believe it must be conceptually similar to [TCP syn-cookies](https://en.wikipedia.org/wiki/SYN_cookies).

The devil here is hiding on how long the validation token we sent out should remain valid, this really depends on how strong the cryptographic mechanism is. I think it also depends on bandwidth potential attacker can utilize to eventually brute force the token. Perhaps the expiration token time needs to be tunable. Best answer here is to learn from other QUIC stacks.

**Comment by t8m** [comment]
IMO handling the validation token can be fully stateless - just make it a HMAC of the new destination connection ID with a random key set during the library or SSL_CTX initialization. No need to expire anything as this cannot be really brute-forced and expiration happens naturally when the server is restarted and a new key is generated.

**Comment by mattcaswell** [comment]
Our DTLS implementation uses a "cookie" for much the same purpose as QUIC's validation token:

https://github.com/openssl/openssl/blob/59f5f6c73cd2e1e2bd8ef405fdb6fadf0711f639/ssl/d1_lib.c#L623-L671

For DTLS the cookie (i.e. validation token) is actually generated via an application callback. We have an implementation of this in our apps:

https://github.com/openssl/openssl/blob/59f5f6c73cd2e1e2bd8ef405fdb6fadf0711f639/apps/lib/s_cb.c#L833-L925

We might draw some inspiration from how this works.

**Comment by vavroch2010** [comment]
Include tests

**Comment by nhorman** [comment]
We could do exactly what TCP syncookies do, and include a timestamp from the server in place of the "openssltoken" string.  Then when its sent back in the new Initial packet, it can be interrogated against the current time to determine some expiration length.

Simple thing to do would be to make the token string "openssltoken" a uint64_t instead filled out with the value returned by OSSL_time_now(), and in port_validate_token() sompare that time to another call to OSSL_time_now().  If the delta is more than some value (say 120 seconds or so), the token is no longer valid

**Comment by nhorman** [comment]
I think I have a proposal here

What we need is a token format that can do the following:
1) be expired after a configured period (https://datatracker.ietf.org/doc/html/rfc9000#section-8.1.4)
2) be used only once (https://datatracker.ietf.org/doc/html/rfc9000#section-8.1.4)
3) Allow for validation of the client via address correlation (https://datatracker.ietf.org/doc/html/rfc9000#section-8.1.3)

Based on how quic-go does this in token_generator.go what it seems like we need is a token structure that contains the following information

a) a timestamp (for allowing expiration at various times in the future (based on weather it was sent in a retry packet or a NEW_TOKEN packet)
b) Some correlating information to allow address validation (either the dcid of the new connection sent in the new inital packet or in the next initial packet in the case of NEW_TOKEN usage)

In quic-go, retry tokens are marshalled as ASN1 encodings containing the following information:
a) for retry packets, the token consists of the data:
     IsRetryToken: bool (true)
     RemoteAddr: bytes (remote addr of the client requesting the connection
     odcid: bytes (dcid of the first initial connection attempt)
     rscid: bytes (retry source connection id of the connection)
     timestamp: uint64_t (time that the token was minted)

b) for NEW_TOKEN packets:
     IsRetryToken: bool (false)
     RemoteAddr: bytes (remote addr of the client requesting the connection)
     Timestamp: uint64_t (time that the token was minted)

validation in quic go consists of unmarshalling the ASN1 object in the token header field, and doing the following:
a) Validate the remote address to confirm that the address matches the ip address of the client trying to establish the connection
b) validate the time stamp against one of two timeout values.  For retry packet tokens the timeout is very short as its used immediately, for NEW_TOKEN packets the timeout is longer

If any of those checks fail for a retry token, we respond with an INVALID protocol error.  For NEW_TOKEN tokens, we respond with a retry packet.

It seems pretty straightforward to implement in our use case I think

**Comment by Sashan** [comment]
sorry if this is a _captain obvious_ speaking again. the quic server protects token by `TokenProtectorKey`. The token itself is sent to client as a _blob_ which is created by AEAD::encrypt using by server's key, see  [token_protector.go](https://github.com/quic-go/quic-go/blob/master/internal/handshake/token_protector.go)

**Comment by nhorman** [comment]
@Sashan I'm sorry, I don't think I understand what you are suggesting here.  I agree with your assertion that quic-go uses the TokenProtectorKey, which is encrypted with AES-128-GCM (I think).  Thats the same thing we do.  The current difference (again, my understanding) is in the contents of the decrypted object.  We current use a blob that decrypts to the string openssltoken + the dcid of the connection, whereas quic go uses a variable structure based on weather we're populating a NEW_TOKEN frame or a retry frame (which include respectively, the source ip, and a timestamp, or the source ip, timestamp and dcid/scid values).

Is there somewhere we're in disagreement on this?

**Comment by Sashan** [comment]
the server sends validation token and appends so called integrity tag to it. This is thiscrbed in [RFC9001](https://datatracker.ietf.org/doc/html/rfc9001#name-retry-packet-integrity) Client uses integrity tag to validate token sent by server is valid. Client then sends token back to server in initial packet without integrity tag. The server should protect (read encrypt) the token to provide integrity and confidentiality. the current naive token we have is plain text.

**Comment by nhorman** [comment]
Crap, you're right, we should fix that up in this issue while we correct the token layout

**Comment by Sashan** [comment]
The validation token must also include source connection ID used in retry packet. we will need this piece
of information later when implementing changes covered by #928

**Comment by nhorman** [comment]
closing issue, as primary task is completed.  Remaining issues to be addressed in #945
