### ISSUE TITLE
Remove RETRY_SCID transport parameter from QUIC stack

### ISSUE THREAD

**Issue by nhorman** [openssl/project#917]
In investigating the quic address validation feature, using @Sashan draft pr, plus hack changes from #915 and #916, I encountered the following error:

reproducer:
```
server:
quic-client-block 8888 ../../test/certs/servercert.pem ../../test/certs/serverkey.pem

client:
SSLKEYLOGFILE=./keylog.txt ./quic-client-block 127.0.0.1 8888
```

With the above changes the TLS handshake failed with the following error:
![Screenshot from 2024-11-05 14-13-40](https://github.com/user-attachments/assets/9eb8ee07-8bb6-4222-9ac2-e462fc20a2db)

The client closes the connection with a TRANSPORT_PARAMETER_ERROR indicating that the RETRY_SCID  transport parameter was not included in the quic transport parameter set of the server hello message.
this transport parameter is not part of the QUIC RFC specifically, but rather part of the QUIC retry offload draft rfc:
https://datatracker.ietf.org/doc/html/draft-ietf-quic-retry-offload

Unfortunately this RFC has not become ratified, and has not been updated since 2022.  Given that it appears that there is no longer any activity on this RFC, it seems to me that implementing it may cause compatibility errors with other implementations, and as such, we should just remove support for it

The task here then is to remove all references to QUIC_TPARAM_RETRY_SCID

**Comment by Sashan** [comment]
This makes sense. I think we need to figure out why client is happy to talk to quiche server (which also sends RETRY packet to validate client), while the same client fails to talk to server which runs OpenSSL QUIC stack. I just wonder what quiche is doing differently so client is happy with it.

**Comment by nhorman** [comment]
I think the answer is, in regards to this issue specifically, that quiche doesn't support the retry offload RFC either.  That is to say, its server doesn't send the retry cid transport parameter, nor does its client validate that that transport parameter exists, which is what we probably should do, at least until hardware exists that generally supports this type of offload

**Comment by t8m** [comment]
Huh? I see retry source connection id transport parameter mentioned in: https://www.ietf.org/rfc/rfc9000.html#cid-auth

An endpoint MUST treat the following as a connection error of type TRANSPORT_PARAMETER_ERROR or PROTOCOL_VIOLATION:
absence of the retry_source_connection_id transport parameter from the server after receiving a Retry packet,
presence of the retry_source_connection_id transport parameter when no Retry packet was received, ora mismatch between values received from a peer in these transport parameters and the value sent in the corresponding Destination or Source Connection ID fields of Initial packets.
