### ISSUE TITLE
Write a server supporting hq interop alpns that can serve multiple http1.0 requests based on filename paths

### ISSUE THREAD

**Issue by vavroch2010** [openssl/project#922]

**Comment by mattcaswell** [comment]
Just a thought on this: quic-server-nonblock.c was designed primarily as a demo application, and as the basis for our guide page on how to write such an application. Augmenting it too far starts to make the demo more complicated than it needs to be and subvert its original intent. For that reason it might be better to create a new application specifically targeted for the interop testing purpose (which could be based initially on quic-server-nonblock.c).

**Comment by nhorman** [comment]
I've got a quic-hq-interop-server draft in https://github.com/nhorman/openssl/tree/quic-server-interop if we want to use that instead, but this is currently predicated on us implementing [server version negotiation](https://github.com/openssl/project/issues/921) to allow our server code to work with the interoperability test harness

**Comment by nhorman** [comment]
Note  I've added a second PR here, the first actually creates the needed infrastructure to run tests as a server, and the second enables CI to run the interop tests nightly using a container built from the feature/quic-server branch
