### ISSUE TITLE
need to add test which makes sure TLS KeyUpdate message properly

### ISSUE THREAD

**Issue by Sashan** [openssl/project#923]
we need to have test which veryfies channel replies with connection error of type 0x010a for TLS KeyUpdate message.

code in quic stack is there, which just missing a test.

we will have to figure out how to use fault injector for this.
https://github.com/openssl/project/issues/899

**Comment by mattcaswell** [comment]
@Sashan - we have such a test:

https://github.com/openssl/openssl/blob/eaf4da97c9b9c09a407b9f1a47ad7dd99c05884c/test/quic_multistream_test.c#L4789-L4809

I think this issue can just be closed?

**Comment by t8m** [comment]
> I think this issue can just be closed?

Yeah. Closing.
