### ISSUE TITLE
Add chrome browser client to our interop testing

### ISSUE THREAD

**Issue by nhorman** [openssl/project#937]
There is a desire to be able to add the chrome web browser as a client in our interoperability testing.  Doing so however will be somewhat "special".  Whereas most of the tests in the quic-interop-runner are mean to be used with the "hq-interop" alpn, chrome is only going to support the h3 alpn, as it is standardized.  As such the use of chrome as a client should be tailored to only run the http3 test in the runner.  This should be sufficient for interop testing however.

To accomplish this, we need to:

- [ ] Augment our interop container to build an http3 server - we  can likely use the ossl-nghttp3-demo-server here, but it will require modification to do actual serving of files rather than just serving a fixed string
- [ ] Augment the interop container entrypoint to run the nginx server for the http3 test when running in a server role
- [ ] Build a second container housing chrome to be run in headless mode as a client only.  House the container on quay, where our current openssl container is stored.  This new container should contain an entrypoint simmilar to our openssl container, but only be responsive to the http3 test in a client role
- [ ] augment the implementations.json file to include the chrome container above in a client role.  Much like the current ci job, we will have to patch this in locally, as the upstream project is currently not accepting new clients/servers
- [ ] update the regular ci job (run_quic_interop.yaml) to run the chrome container as a client and openssl as a server

**Comment by vavroch2010** [comment]
Handled in #950
