### ISSUE TITLE
Analyze interop failures and log issues for them

### ISSUE THREAD

**Issue by vavroch2010** [openssl/project#944]
Currently looking at minimal test passage to claim MVP:
interop with openssl client and openssl server:

- [x] #948
- [x] transfer test passed
- [x] longrtt test passed
- [x] chacha20 test passed
- [x] #949
- [x] retry test passed
- [x] resumption test passed
- [ ] zerortt test is currently unsupported by both quic client and server
- [x] #950
- [x] blackhole test passed
- [ ] #951
- [ ] ecn test currently unsupported
- [x] #952
- [x] #953
- [x] transferloss test passed
- [x] #954
- [x] transfercorruption test passed
- [x] #955
- [ ] v2 test currently unsupported
- [x] https://github.com/openssl/project/issues/962

Additionally, our throughput on the goodput test is 9366 kbps while our crosstraffic test is 2301 kbps, which is probably good for MVP

Note: zerortt, ecn and v2 tests are not required for MVP, and can likely be skipped

**Comment by nhorman** [comment]
Additional note: The chrome only preforms the http3 test as a client, and it fails for the same reason the openssl-openssl http3 test above does (see associated issue)
