### ISSUE TITLE
Windows CI fix

### ISSUE THREAD

**Issue by vavroch2010** [openssl/project#946]
As for the windows failures, I think you may be having a problem with the timestamp comparison. IIRC windows timestamping is much more coarse than it is on linux, so it may be possible that you are comparing two timestamps that are equal (especially given that transport of these packets in the test environment happens almost instantly, rather than having some network delay introduced). May be worth checking ossl_time_compare in port_validate_token for being strictly less than zero, rather than >= zero

**Comment by nhorman** [comment]
Note: The draft PR attached shows that changing the time comparison fixes the windows test issues, it should be rolled into @andrewkdinh retry branch https://github.com/openssl/openssl/pull/26048
