### ISSUE TITLE
interop http3 test is currently unsupported

### ISSUE THREAD

**Issue by nhorman** [openssl/project#950]
While the quic-hq-interop-server handles most interop test cases, it does not handle the http3 test case, as http3 communication is significantly more complex than http 0.9/hq-interop.

What we need here is to adapt the nghttp3 server demo to allow the serving of multiple get requests from a client, and then augment the container run_endpoint.sh script for the server role to run this server instead of the interop server for the http3 test.  This will allow us to preform the http3 test with any client, including the chrome client

**Comment by nhorman** [comment]
I have a sample branch here for this:
https://github.com/nhorman/openssl/tree/http3-server

Its based on the work that was done here https://github.com/openssl/openssl/pull/25859 by @jfclere

With some modifications, notably:
* modification of the server to support an environmentally defined content folder
* modification of the server to send files with a content-length header and a content-type header of application/octet-stream

The openssl server passes the http3 interop test with the chrome browser client

Unsure how best to move forward with this at the moment, as his inclusion of the server is pending in pr #25895.  Will ask if he wants to incorporate those changes

**Comment by jfclere** [comment]
I have merged those changes to my PR, I have not yet tried to run the interop tests, I will look later.

**Comment by nhorman** [comment]
Thank you @jfclere !  FWIW, that branch where I sent you the needed commits has additional changes which enable interop tests via the container built from tests/quic-openssl-docker.  You are welcome to use that branch, replacing my copy of the server with your own.  From there you can run the quic-interop runner (don't forget to augment the implementations.json file to show openssl as having "both" client and server roles), and it should pass the http3 test with any of the supported http3 client roles (of particular note is that chrome passes with in this environment).

**Comment by jfclere** [comment]
please check https://github.com/openssl/openssl/pull/26193 to finish it,
